#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChemSpider.Sql
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ChemSpider")]
	public partial class ChemSpiderSqlDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertdeposition(deposition instance);
    partial void Updatedeposition(deposition instance);
    partial void Deletedeposition(deposition instance);
    partial void Insertdepositions_track(depositions_track instance);
    partial void Updatedepositions_track(depositions_track instance);
    partial void Deletedepositions_track(depositions_track instance);
    partial void Insertsynonym(synonym instance);
    partial void Updatesynonym(synonym instance);
    partial void Deletesynonym(synonym instance);
    #endregion
			
		public ChemSpiderSqlDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ChemSpiderSqlDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ChemSpiderSqlDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ChemSpiderSqlDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<deposition> depositions
		{
			get
			{
				return this.GetTable<deposition>();
			}
		}
		
		public System.Data.Linq.Table<depositions_track> depositions_tracks
		{
			get
			{
				return this.GetTable<depositions_track>();
			}
		}
		
		public System.Data.Linq.Table<v_filter_run> v_filter_runs
		{
			get
			{
				return this.GetTable<v_filter_run>();
			}
		}
		
		public System.Data.Linq.Table<v_filter> v_filters
		{
			get
			{
				return this.GetTable<v_filter>();
			}
		}
		
		public System.Data.Linq.Table<synonym> synonyms
		{
			get
			{
				return this.GetTable<synonym>();
			}
		}
		
		public System.Data.Linq.Table<v_transaction> v_transactions
		{
			get
			{
				return this.GetTable<v_transaction>();
			}
		}
		
		public System.Data.Linq.Table<v_deposition> v_depositions
		{
			get
			{
				return this.GetTable<v_deposition>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DeleteSynonym")]
		public int DeleteSynonym([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> syn_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), syn_id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UndeleteSynonym")]
		public int UndeleteSynonym([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> syn_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), syn_id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.filter_run_create")]
		public int filter_run_create([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> fid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="UniqueIdentifier")] System.Nullable<System.Guid> trn_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> undo_frid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fid, trn_id, undo_frid);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.filter_update")]
		public int filter_update([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> fid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string description, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string search_handler, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Xml")] System.Xml.Linq.XElement search_options, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string object_type, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string action_handler, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Xml")] System.Xml.Linq.XElement action_options, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarBinary(MAX)")] System.Data.Linq.Binary ui_state, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> deleted_yn)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fid, name, description, search_handler, search_options, object_type, action_handler, action_options, ui_state, deleted_yn);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.filter_create")]
		public int filter_create([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string description, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> creator, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string search_handler, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Xml")] System.Xml.Linq.XElement search_options, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string object_type, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string action_handler, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Xml")] System.Xml.Linq.XElement action_options, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarBinary(MAX)")] System.Data.Linq.Binary ui_state, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> fid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name, description, creator, search_handler, search_options, object_type, action_handler, action_options, ui_state, fid);
			fid = ((System.Nullable<int>)(result.GetParameterValue(9)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UpdateSynonym")]
		public int UpdateSynonym([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> syn_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(448)")] string synonym, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(2)")] string lang_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Xml")] System.Xml.Linq.XElement flags, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> merge_options, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> updating_syn_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> action_id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), syn_id, synonym, lang_id, flags, merge_options, updating_syn_id, action_id);
			updating_syn_id = ((System.Nullable<int>)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SetDepositionSuppInfo")]
		public int SetDepositionSuppInfo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> dep_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Xml")] System.Xml.Linq.XElement supp_info)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dep_id, supp_info);
			return ((int)(result.ReturnValue));
		}

        [global::System.Data.Linq.Mapping.FunctionAttribute(Name = "dbo.DepricateCompound")]
        public int DepricateCompound([global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "Int")] System.Nullable<int> cmp_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "Int")] System.Nullable<int> usr_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "Bit")] System.Nullable<bool> depricated_yn)
        {
            IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cmp_id, usr_id, depricated_yn);
            return ((int)(result.ReturnValue));
        }

        [global::System.Data.Linq.Mapping.FunctionAttribute(Name = "dbo.DeprecateCompoundsSynonym")]
        public int DeprecateCompoundsSynonym([global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "Int")] System.Nullable<int> cmp_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "Int")] System.Nullable<int> syn_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "Int")] System.Nullable<int> usr_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType = "Bit")] System.Nullable<bool> deleted_yn)
        {
            IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cmp_id, syn_id, usr_id, deleted_yn);
            return ((int)(result.ReturnValue));
        }
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.depositions")]
	public partial class deposition : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _dep_id;
		
		private System.DateTime _date_submitted;
		
		private System.Nullable<System.DateTime> _date_published;
		
		private char _status;
		
		private int _dsn_id;
		
		private int _usr_id;
		
		private string _file_name;
		
		private bool _open_yn;
		
		private string _description;
		
		private bool _synonyms_confirmed;
		
		private string _orig_file_name;
		
		private System.Nullable<int> _num_records;
		
		private string _typ;
		
		private System.Xml.Linq.XElement _supp_info;
		
		private System.Nullable<System.DateTime> _date_locked;
		
		private System.Nullable<int> _col_id;
		
		private string _file_encoding;
		
		private bool _dsn_update_yn;
		
		private string _data_dir;
		
		private int _update_flags;
		
		private EntitySet<depositions_track> _depositions_tracks;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ondep_idChanging(int value);
    partial void Ondep_idChanged();
    partial void Ondate_submittedChanging(System.DateTime value);
    partial void Ondate_submittedChanged();
    partial void Ondate_publishedChanging(System.Nullable<System.DateTime> value);
    partial void Ondate_publishedChanged();
    partial void OnstatusChanging(char value);
    partial void OnstatusChanged();
    partial void Ondsn_idChanging(int value);
    partial void Ondsn_idChanged();
    partial void Onusr_idChanging(int value);
    partial void Onusr_idChanged();
    partial void Onfile_nameChanging(string value);
    partial void Onfile_nameChanged();
    partial void Onopen_ynChanging(bool value);
    partial void Onopen_ynChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void Onsynonyms_confirmedChanging(bool value);
    partial void Onsynonyms_confirmedChanged();
    partial void Onorig_file_nameChanging(string value);
    partial void Onorig_file_nameChanged();
    partial void Onnum_recordsChanging(System.Nullable<int> value);
    partial void Onnum_recordsChanged();
    partial void OntypChanging(string value);
    partial void OntypChanged();
    partial void Onsupp_infoChanging(System.Xml.Linq.XElement value);
    partial void Onsupp_infoChanged();
    partial void Ondate_lockedChanging(System.Nullable<System.DateTime> value);
    partial void Ondate_lockedChanged();
    partial void Oncol_idChanging(System.Nullable<int> value);
    partial void Oncol_idChanged();
    partial void Onfile_encodingChanging(string value);
    partial void Onfile_encodingChanged();
    partial void Ondsn_update_ynChanging(bool value);
    partial void Ondsn_update_ynChanged();
    partial void Ondata_dirChanging(string value);
    partial void Ondata_dirChanged();
    partial void Onupdate_flagsChanging(int value);
    partial void Onupdate_flagsChanged();
    #endregion
		
		public deposition()
		{
			this._depositions_tracks = new EntitySet<depositions_track>(new Action<depositions_track>(this.attach_depositions_tracks), new Action<depositions_track>(this.detach_depositions_tracks));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dep_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int dep_id
		{
			get
			{
				return this._dep_id;
			}
			set
			{
				if ((this._dep_id != value))
				{
					this.Ondep_idChanging(value);
					this.SendPropertyChanging();
					this._dep_id = value;
					this.SendPropertyChanged("dep_id");
					this.Ondep_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_submitted", DbType="DateTime NOT NULL")]
		public System.DateTime date_submitted
		{
			get
			{
				return this._date_submitted;
			}
			set
			{
				if ((this._date_submitted != value))
				{
					this.Ondate_submittedChanging(value);
					this.SendPropertyChanging();
					this._date_submitted = value;
					this.SendPropertyChanged("date_submitted");
					this.Ondate_submittedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_published", DbType="DateTime")]
		public System.Nullable<System.DateTime> date_published
		{
			get
			{
				return this._date_published;
			}
			set
			{
				if ((this._date_published != value))
				{
					this.Ondate_publishedChanging(value);
					this.SendPropertyChanging();
					this._date_published = value;
					this.SendPropertyChanged("date_published");
					this.Ondate_publishedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Char(1) NOT NULL")]
		public char status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dsn_id", DbType="Int NOT NULL")]
		public int dsn_id
		{
			get
			{
				return this._dsn_id;
			}
			set
			{
				if ((this._dsn_id != value))
				{
					this.Ondsn_idChanging(value);
					this.SendPropertyChanging();
					this._dsn_id = value;
					this.SendPropertyChanged("dsn_id");
					this.Ondsn_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usr_id", DbType="Int NOT NULL")]
		public int usr_id
		{
			get
			{
				return this._usr_id;
			}
			set
			{
				if ((this._usr_id != value))
				{
					this.Onusr_idChanging(value);
					this.SendPropertyChanging();
					this._usr_id = value;
					this.SendPropertyChanged("usr_id");
					this.Onusr_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_file_name", DbType="VarChar(300) NOT NULL", CanBeNull=false)]
		public string file_name
		{
			get
			{
				return this._file_name;
			}
			set
			{
				if ((this._file_name != value))
				{
					this.Onfile_nameChanging(value);
					this.SendPropertyChanging();
					this._file_name = value;
					this.SendPropertyChanged("file_name");
					this.Onfile_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_open_yn", DbType="Bit NOT NULL")]
		public bool open_yn
		{
			get
			{
				return this._open_yn;
			}
			set
			{
				if ((this._open_yn != value))
				{
					this.Onopen_ynChanging(value);
					this.SendPropertyChanging();
					this._open_yn = value;
					this.SendPropertyChanged("open_yn");
					this.Onopen_ynChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_synonyms_confirmed", DbType="Bit NOT NULL")]
		public bool synonyms_confirmed
		{
			get
			{
				return this._synonyms_confirmed;
			}
			set
			{
				if ((this._synonyms_confirmed != value))
				{
					this.Onsynonyms_confirmedChanging(value);
					this.SendPropertyChanging();
					this._synonyms_confirmed = value;
					this.SendPropertyChanged("synonyms_confirmed");
					this.Onsynonyms_confirmedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_orig_file_name", DbType="VarChar(300)")]
		public string orig_file_name
		{
			get
			{
				return this._orig_file_name;
			}
			set
			{
				if ((this._orig_file_name != value))
				{
					this.Onorig_file_nameChanging(value);
					this.SendPropertyChanging();
					this._orig_file_name = value;
					this.SendPropertyChanged("orig_file_name");
					this.Onorig_file_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_num_records", DbType="Int")]
		public System.Nullable<int> num_records
		{
			get
			{
				return this._num_records;
			}
			set
			{
				if ((this._num_records != value))
				{
					this.Onnum_recordsChanging(value);
					this.SendPropertyChanging();
					this._num_records = value;
					this.SendPropertyChanged("num_records");
					this.Onnum_recordsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_typ", DbType="VarChar(3)")]
		public string typ
		{
			get
			{
				return this._typ;
			}
			set
			{
				if ((this._typ != value))
				{
					this.OntypChanging(value);
					this.SendPropertyChanging();
					this._typ = value;
					this.SendPropertyChanged("typ");
					this.OntypChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_supp_info", DbType="Xml", UpdateCheck=UpdateCheck.Never)]
		public System.Xml.Linq.XElement supp_info
		{
			get
			{
				return this._supp_info;
			}
			set
			{
				if ((this._supp_info != value))
				{
					this.Onsupp_infoChanging(value);
					this.SendPropertyChanging();
					this._supp_info = value;
					this.SendPropertyChanged("supp_info");
					this.Onsupp_infoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_locked", DbType="DateTime")]
		public System.Nullable<System.DateTime> date_locked
		{
			get
			{
				return this._date_locked;
			}
			set
			{
				if ((this._date_locked != value))
				{
					this.Ondate_lockedChanging(value);
					this.SendPropertyChanging();
					this._date_locked = value;
					this.SendPropertyChanged("date_locked");
					this.Ondate_lockedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_col_id", DbType="Int")]
		public System.Nullable<int> col_id
		{
			get
			{
				return this._col_id;
			}
			set
			{
				if ((this._col_id != value))
				{
					this.Oncol_idChanging(value);
					this.SendPropertyChanging();
					this._col_id = value;
					this.SendPropertyChanged("col_id");
					this.Oncol_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_file_encoding", DbType="VarChar(50)")]
		public string file_encoding
		{
			get
			{
				return this._file_encoding;
			}
			set
			{
				if ((this._file_encoding != value))
				{
					this.Onfile_encodingChanging(value);
					this.SendPropertyChanging();
					this._file_encoding = value;
					this.SendPropertyChanged("file_encoding");
					this.Onfile_encodingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dsn_update_yn", DbType="Bit NOT NULL")]
		public bool dsn_update_yn
		{
			get
			{
				return this._dsn_update_yn;
			}
			set
			{
				if ((this._dsn_update_yn != value))
				{
					this.Ondsn_update_ynChanging(value);
					this.SendPropertyChanging();
					this._dsn_update_yn = value;
					this.SendPropertyChanged("dsn_update_yn");
					this.Ondsn_update_ynChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_dir", DbType="VarChar(150)")]
		public string data_dir
		{
			get
			{
				return this._data_dir;
			}
			set
			{
				if ((this._data_dir != value))
				{
					this.Ondata_dirChanging(value);
					this.SendPropertyChanging();
					this._data_dir = value;
					this.SendPropertyChanged("data_dir");
					this.Ondata_dirChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_update_flags", DbType="Int NOT NULL")]
		public int update_flags
		{
			get
			{
				return this._update_flags;
			}
			set
			{
				if ((this._update_flags != value))
				{
					this.Onupdate_flagsChanging(value);
					this.SendPropertyChanging();
					this._update_flags = value;
					this.SendPropertyChanged("update_flags");
					this.Onupdate_flagsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="deposition_depositions_track", Storage="_depositions_tracks", ThisKey="dep_id", OtherKey="dep_id")]
		public EntitySet<depositions_track> depositions_tracks
		{
			get
			{
				return this._depositions_tracks;
			}
			set
			{
				this._depositions_tracks.Assign(value);
			}
		}

	
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_depositions_tracks(depositions_track entity)
		{
			this.SendPropertyChanging();
			entity.deposition = this;
		}
		
		private void detach_depositions_tracks(depositions_track entity)
		{
			this.SendPropertyChanging();
			entity.deposition = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.depositions_track")]
	public partial class depositions_track : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _dtid;
		
		private int _dep_id;
		
		private char _status;
		
		private System.DateTime _date;
		
		private System.Nullable<int> _usr_id;
		
		private EntityRef<deposition> _deposition;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OndtidChanging(int value);
    partial void OndtidChanged();
    partial void Ondep_idChanging(int value);
    partial void Ondep_idChanged();
    partial void OnstatusChanging(char value);
    partial void OnstatusChanged();
    partial void OndateChanging(System.DateTime value);
    partial void OndateChanged();
    partial void Onusr_idChanging(System.Nullable<int> value);
    partial void Onusr_idChanged();
    #endregion
		
		public depositions_track()
		{
			this._deposition = default(EntityRef<deposition>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int dtid
		{
			get
			{
				return this._dtid;
			}
			set
			{
				if ((this._dtid != value))
				{
					this.OndtidChanging(value);
					this.SendPropertyChanging();
					this._dtid = value;
					this.SendPropertyChanged("dtid");
					this.OndtidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dep_id", DbType="Int NOT NULL")]
		public int dep_id
		{
			get
			{
				return this._dep_id;
			}
			set
			{
				if ((this._dep_id != value))
				{
					if (this._deposition.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ondep_idChanging(value);
					this.SendPropertyChanging();
					this._dep_id = value;
					this.SendPropertyChanged("dep_id");
					this.Ondep_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Char(1) NOT NULL")]
		public char status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="DateTime NOT NULL")]
		public System.DateTime date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usr_id", DbType="Int")]
		public System.Nullable<int> usr_id
		{
			get
			{
				return this._usr_id;
			}
			set
			{
				if ((this._usr_id != value))
				{
					this.Onusr_idChanging(value);
					this.SendPropertyChanging();
					this._usr_id = value;
					this.SendPropertyChanged("usr_id");
					this.Onusr_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="deposition_depositions_track", Storage="_deposition", ThisKey="dep_id", OtherKey="dep_id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public deposition deposition
		{
			get
			{
				return this._deposition.Entity;
			}
			set
			{
				deposition previousValue = this._deposition.Entity;
				if (((previousValue != value) 
							|| (this._deposition.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._deposition.Entity = null;
						previousValue.depositions_tracks.Remove(this);
					}
					this._deposition.Entity = value;
					if ((value != null))
					{
						value.depositions_tracks.Add(this);
						this._dep_id = value.dep_id;
					}
					else
					{
						this._dep_id = default(int);
					}
					this.SendPropertyChanged("deposition");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_filter_runs")]
	public partial class v_filter_run
	{
		
		private int _frid;
		
		private int _fid;
		
		private System.Guid _trn_id;
		
		private System.Nullable<int> _undo_frid;
		
		public v_filter_run()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_frid", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int frid
		{
			get
			{
				return this._frid;
			}
			set
			{
				if ((this._frid != value))
				{
					this._frid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fid", DbType="Int NOT NULL")]
		public int fid
		{
			get
			{
				return this._fid;
			}
			set
			{
				if ((this._fid != value))
				{
					this._fid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trn_id", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid trn_id
		{
			get
			{
				return this._trn_id;
			}
			set
			{
				if ((this._trn_id != value))
				{
					this._trn_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_undo_frid", DbType="Int")]
		public System.Nullable<int> undo_frid
		{
			get
			{
				return this._undo_frid;
			}
			set
			{
				if ((this._undo_frid != value))
				{
					this._undo_frid = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_filters")]
	public partial class v_filter
	{
		
		private int _fid;
		
		private string _name;
		
		private string _description;
		
		private string _search_handler;
		
		private System.Xml.Linq.XElement _search_options;
		
		private System.Data.Linq.Binary _ui_state;
		
		private string _object_type;
		
		private string _action_handler;
		
		private System.Xml.Linq.XElement _action_options;
		
		private bool _deleted_yn;
		
		private int _creator;
		
		private System.Nullable<int> _frid;
		
		public v_filter()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fid", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int fid
		{
			get
			{
				return this._fid;
			}
			set
			{
				if ((this._fid != value))
				{
					this._fid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="NVarChar(200)")]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this._description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_search_handler", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string search_handler
		{
			get
			{
				return this._search_handler;
			}
			set
			{
				if ((this._search_handler != value))
				{
					this._search_handler = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_search_options", DbType="Xml NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Xml.Linq.XElement search_options
		{
			get
			{
				return this._search_options;
			}
			set
			{
				if ((this._search_options != value))
				{
					this._search_options = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ui_state", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary ui_state
		{
			get
			{
				return this._ui_state;
			}
			set
			{
				if ((this._ui_state != value))
				{
					this._ui_state = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_object_type", DbType="VarChar(30)")]
		public string object_type
		{
			get
			{
				return this._object_type;
			}
			set
			{
				if ((this._object_type != value))
				{
					this._object_type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_action_handler", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string action_handler
		{
			get
			{
				return this._action_handler;
			}
			set
			{
				if ((this._action_handler != value))
				{
					this._action_handler = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_action_options", DbType="Xml", UpdateCheck=UpdateCheck.Never)]
		public System.Xml.Linq.XElement action_options
		{
			get
			{
				return this._action_options;
			}
			set
			{
				if ((this._action_options != value))
				{
					this._action_options = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deleted_yn", DbType="Bit NOT NULL")]
		public bool deleted_yn
		{
			get
			{
				return this._deleted_yn;
			}
			set
			{
				if ((this._deleted_yn != value))
				{
					this._deleted_yn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_creator", DbType="Int NOT NULL")]
		public int creator
		{
			get
			{
				return this._creator;
			}
			set
			{
				if ((this._creator != value))
				{
					this._creator = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_frid", DbType="Int")]
		public System.Nullable<int> frid
		{
			get
			{
				return this._frid;
			}
			set
			{
				if ((this._frid != value))
				{
					this._frid = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.synonyms")]
	public partial class synonym : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _syn_id;
		
		private string _synonym1;
		
		private string _lang_id1;
		
		private bool _checked_yn;
		
		private bool _deleted_yn;
		
		private System.DateTime _date_created;
		
		private System.Nullable<System.DateTime> _date_updated;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onsyn_idChanging(int value);
    partial void Onsyn_idChanged();
    partial void Onsynonym1Changing(string value);
    partial void Onsynonym1Changed();
    partial void Onlang_id1Changing(string value);
    partial void Onlang_id1Changed();
    partial void Onchecked_ynChanging(bool value);
    partial void Onchecked_ynChanged();
    partial void Ondeleted_ynChanging(bool value);
    partial void Ondeleted_ynChanged();
    partial void Ondate_createdChanging(System.DateTime value);
    partial void Ondate_createdChanged();
    partial void Ondate_updatedChanging(System.Nullable<System.DateTime> value);
    partial void Ondate_updatedChanged();
    #endregion
		
		public synonym()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_syn_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int syn_id
		{
			get
			{
				return this._syn_id;
			}
			set
			{
				if ((this._syn_id != value))
				{
					this.Onsyn_idChanging(value);
					this.SendPropertyChanging();
					this._syn_id = value;
					this.SendPropertyChanged("syn_id");
					this.Onsyn_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="synonym", Storage="_synonym1", DbType="NVarChar(448) NOT NULL", CanBeNull=false)]
		public string synonym1
		{
			get
			{
				return this._synonym1;
			}
			set
			{
				if ((this._synonym1 != value))
				{
					this.Onsynonym1Changing(value);
					this.SendPropertyChanging();
					this._synonym1 = value;
					this.SendPropertyChanged("synonym1");
					this.Onsynonym1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lang_id1", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string lang_id1
		{
			get
			{
				return this._lang_id1;
			}
			set
			{
				if ((this._lang_id1 != value))
				{
					this.Onlang_id1Changing(value);
					this.SendPropertyChanging();
					this._lang_id1 = value;
					this.SendPropertyChanged("lang_id1");
					this.Onlang_id1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_checked_yn", DbType="Bit NOT NULL")]
		public bool checked_yn
		{
			get
			{
				return this._checked_yn;
			}
			set
			{
				if ((this._checked_yn != value))
				{
					this.Onchecked_ynChanging(value);
					this.SendPropertyChanging();
					this._checked_yn = value;
					this.SendPropertyChanged("checked_yn");
					this.Onchecked_ynChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deleted_yn", DbType="Bit NOT NULL")]
		public bool deleted_yn
		{
			get
			{
				return this._deleted_yn;
			}
			set
			{
				if ((this._deleted_yn != value))
				{
					this.Ondeleted_ynChanging(value);
					this.SendPropertyChanging();
					this._deleted_yn = value;
					this.SendPropertyChanged("deleted_yn");
					this.Ondeleted_ynChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_created", DbType="DateTime NOT NULL")]
		public System.DateTime date_created
		{
			get
			{
				return this._date_created;
			}
			set
			{
				if ((this._date_created != value))
				{
					this.Ondate_createdChanging(value);
					this.SendPropertyChanging();
					this._date_created = value;
					this.SendPropertyChanged("date_created");
					this.Ondate_createdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_updated", DbType="DateTime")]
		public System.Nullable<System.DateTime> date_updated
		{
			get
			{
				return this._date_updated;
			}
			set
			{
				if ((this._date_updated != value))
				{
					this.Ondate_updatedChanging(value);
					this.SendPropertyChanging();
					this._date_updated = value;
					this.SendPropertyChanged("date_updated");
					this.Ondate_updatedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_transactions")]
	public partial class v_transaction
	{
		
		private System.Guid _trn_id;
		
		private System.Nullable<System.Guid> _ses_id;
		
		private char _type;
		
		private string _address;
		
		private string _referrer;
		
		private System.DateTime _date_started;
		
		private System.Nullable<System.DateTime> _date_updated;
		
		private System.Nullable<double> _progress;
		
		private char _status;
		
		private string _predicate;
		
		private string _message;
		
		private System.Data.Linq.Binary _result_data;
		
		private System.Nullable<bool> _stop;
		
		private System.Nullable<int> _count;
		
		public v_transaction()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trn_id", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid trn_id
		{
			get
			{
				return this._trn_id;
			}
			set
			{
				if ((this._trn_id != value))
				{
					this._trn_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ses_id", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> ses_id
		{
			get
			{
				return this._ses_id;
			}
			set
			{
				if ((this._ses_id != value))
				{
					this._ses_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="Char(1) NOT NULL")]
		public char type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this._type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="VarChar(100)")]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this._address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_referrer", DbType="VarChar(200)")]
		public string referrer
		{
			get
			{
				return this._referrer;
			}
			set
			{
				if ((this._referrer != value))
				{
					this._referrer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_started", DbType="DateTime NOT NULL")]
		public System.DateTime date_started
		{
			get
			{
				return this._date_started;
			}
			set
			{
				if ((this._date_started != value))
				{
					this._date_started = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_updated", DbType="DateTime")]
		public System.Nullable<System.DateTime> date_updated
		{
			get
			{
				return this._date_updated;
			}
			set
			{
				if ((this._date_updated != value))
				{
					this._date_updated = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_progress", DbType="Float")]
		public System.Nullable<double> progress
		{
			get
			{
				return this._progress;
			}
			set
			{
				if ((this._progress != value))
				{
					this._progress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Char(1) NOT NULL")]
		public char status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this._status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_predicate", DbType="VarChar(2000)")]
		public string predicate
		{
			get
			{
				return this._predicate;
			}
			set
			{
				if ((this._predicate != value))
				{
					this._predicate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_message", DbType="VarChar(1000)")]
		public string message
		{
			get
			{
				return this._message;
			}
			set
			{
				if ((this._message != value))
				{
					this._message = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_result_data", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary result_data
		{
			get
			{
				return this._result_data;
			}
			set
			{
				if ((this._result_data != value))
				{
					this._result_data = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stop", DbType="Bit")]
		public System.Nullable<bool> stop
		{
			get
			{
				return this._stop;
			}
			set
			{
				if ((this._stop != value))
				{
					this._stop = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_count", DbType="Int")]
		public System.Nullable<int> count
		{
			get
			{
				return this._count;
			}
			set
			{
				if ((this._count != value))
				{
					this._count = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.v_depositions")]
	public partial class v_deposition
	{
		
		private int _dep_id;
		
		private System.DateTime _date_submitted;
		
		private System.Nullable<System.DateTime> _date_published;
		
		private char _status;
		
		private string _status_tag;
		
		private int _dsn_id;
		
		private int _usr_id;
		
		private string _file_name;
		
		private string _description;
		
		private System.Nullable<int> _num_records;
		
		private string _orig_file_name;
		
		private System.Xml.Linq.XElement _supp_info;
		
		private string _file_encoding;
		
		private bool _dsn_update_yn;
		
		private bool _synonyms_confirmed;
		
		private string _typ;
		
		private string _data_dir;
		
		private string _dataset_version;
		
		private System.Nullable<System.DateTime> _dataset_created;
		
		private string _dataset_imported_from;
		
		private string _dataset_license;
		
		private string _dataset_uri_space;
		
		private string _dataset_void_uri;
		
		private System.Nullable<int> _mapped_fields_count;
		
		private System.Nullable<int> _fields_count;
		
		private string _ds_name;
		
		private System.Nullable<int> _files_count;
		
		private System.Nullable<System.DateTime> _date_locked;
		
		private int _update_flags;
		
		private System.Nullable<int> _progress;
		
		private string _submitter;
		
		private bool _is_legacy;
		
		public v_deposition()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dep_id", DbType="Int NOT NULL")]
		public int dep_id
		{
			get
			{
				return this._dep_id;
			}
			set
			{
				if ((this._dep_id != value))
				{
					this._dep_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_submitted", DbType="DateTime NOT NULL")]
		public System.DateTime date_submitted
		{
			get
			{
				return this._date_submitted;
			}
			set
			{
				if ((this._date_submitted != value))
				{
					this._date_submitted = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_published", DbType="DateTime")]
		public System.Nullable<System.DateTime> date_published
		{
			get
			{
				return this._date_published;
			}
			set
			{
				if ((this._date_published != value))
				{
					this._date_published = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Char(1) NOT NULL")]
		public char status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this._status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status_tag", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string status_tag
		{
			get
			{
				return this._status_tag;
			}
			set
			{
				if ((this._status_tag != value))
				{
					this._status_tag = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dsn_id", DbType="Int NOT NULL")]
		public int dsn_id
		{
			get
			{
				return this._dsn_id;
			}
			set
			{
				if ((this._dsn_id != value))
				{
					this._dsn_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usr_id", DbType="Int NOT NULL")]
		public int usr_id
		{
			get
			{
				return this._usr_id;
			}
			set
			{
				if ((this._usr_id != value))
				{
					this._usr_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_file_name", DbType="VarChar(300) NOT NULL", CanBeNull=false)]
		public string file_name
		{
			get
			{
				return this._file_name;
			}
			set
			{
				if ((this._file_name != value))
				{
					this._file_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this._description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_num_records", DbType="Int")]
		public System.Nullable<int> num_records
		{
			get
			{
				return this._num_records;
			}
			set
			{
				if ((this._num_records != value))
				{
					this._num_records = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_orig_file_name", DbType="VarChar(300)")]
		public string orig_file_name
		{
			get
			{
				return this._orig_file_name;
			}
			set
			{
				if ((this._orig_file_name != value))
				{
					this._orig_file_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_supp_info", DbType="Xml", UpdateCheck=UpdateCheck.Never)]
		public System.Xml.Linq.XElement supp_info
		{
			get
			{
				return this._supp_info;
			}
			set
			{
				if ((this._supp_info != value))
				{
					this._supp_info = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_file_encoding", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string file_encoding
		{
			get
			{
				return this._file_encoding;
			}
			set
			{
				if ((this._file_encoding != value))
				{
					this._file_encoding = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dsn_update_yn", DbType="Bit NOT NULL")]
		public bool dsn_update_yn
		{
			get
			{
				return this._dsn_update_yn;
			}
			set
			{
				if ((this._dsn_update_yn != value))
				{
					this._dsn_update_yn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_synonyms_confirmed", DbType="Bit NOT NULL")]
		public bool synonyms_confirmed
		{
			get
			{
				return this._synonyms_confirmed;
			}
			set
			{
				if ((this._synonyms_confirmed != value))
				{
					this._synonyms_confirmed = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_typ", DbType="VarChar(3)")]
		public string typ
		{
			get
			{
				return this._typ;
			}
			set
			{
				if ((this._typ != value))
				{
					this._typ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_dir", DbType="VarChar(150)")]
		public string data_dir
		{
			get
			{
				return this._data_dir;
			}
			set
			{
				if ((this._data_dir != value))
				{
					this._data_dir = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dataset_version", DbType="VarChar(20)")]
		public string dataset_version
		{
			get
			{
				return this._dataset_version;
			}
			set
			{
				if ((this._dataset_version != value))
				{
					this._dataset_version = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dataset_created", DbType="DateTime")]
		public System.Nullable<System.DateTime> dataset_created
		{
			get
			{
				return this._dataset_created;
			}
			set
			{
				if ((this._dataset_created != value))
				{
					this._dataset_created = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dataset_imported_from", DbType="VarChar(300)")]
		public string dataset_imported_from
		{
			get
			{
				return this._dataset_imported_from;
			}
			set
			{
				if ((this._dataset_imported_from != value))
				{
					this._dataset_imported_from = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dataset_license", DbType="VarChar(300)")]
		public string dataset_license
		{
			get
			{
				return this._dataset_license;
			}
			set
			{
				if ((this._dataset_license != value))
				{
					this._dataset_license = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dataset_uri_space", DbType="VarChar(300)")]
		public string dataset_uri_space
		{
			get
			{
				return this._dataset_uri_space;
			}
			set
			{
				if ((this._dataset_uri_space != value))
				{
					this._dataset_uri_space = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dataset_void_uri", DbType="VarChar(300)")]
		public string dataset_void_uri
		{
			get
			{
				return this._dataset_void_uri;
			}
			set
			{
				if ((this._dataset_void_uri != value))
				{
					this._dataset_void_uri = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mapped_fields_count", DbType="Int")]
		public System.Nullable<int> mapped_fields_count
		{
			get
			{
				return this._mapped_fields_count;
			}
			set
			{
				if ((this._mapped_fields_count != value))
				{
					this._mapped_fields_count = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fields_count", DbType="Int")]
		public System.Nullable<int> fields_count
		{
			get
			{
				return this._fields_count;
			}
			set
			{
				if ((this._fields_count != value))
				{
					this._fields_count = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ds_name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string ds_name
		{
			get
			{
				return this._ds_name;
			}
			set
			{
				if ((this._ds_name != value))
				{
					this._ds_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_files_count", DbType="Int")]
		public System.Nullable<int> files_count
		{
			get
			{
				return this._files_count;
			}
			set
			{
				if ((this._files_count != value))
				{
					this._files_count = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_locked", DbType="DateTime")]
		public System.Nullable<System.DateTime> date_locked
		{
			get
			{
				return this._date_locked;
			}
			set
			{
				if ((this._date_locked != value))
				{
					this._date_locked = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_update_flags", DbType="Int NOT NULL")]
		public int update_flags
		{
			get
			{
				return this._update_flags;
			}
			set
			{
				if ((this._update_flags != value))
				{
					this._update_flags = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_progress", DbType="Int")]
		public System.Nullable<int> progress
		{
			get
			{
				return this._progress;
			}
			set
			{
				if ((this._progress != value))
				{
					this._progress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_submitter", DbType="VarChar(201)")]
		public string submitter
		{
			get
			{
				return this._submitter;
			}
			set
			{
				if ((this._submitter != value))
				{
					this._submitter = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_legacy", DbType="Bit NOT NULL")]
		public bool is_legacy
		{
			get
			{
				return this._is_legacy;
			}
			set
			{
				if ((this._is_legacy != value))
				{
					this._is_legacy = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
