// <auto-generated />
namespace RSC.CVSP.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addOrdinalindex : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addOrdinalindex));
        
        string IMigrationMetadata.Id
        {
            get { return "201510141333392_add Ordinal index"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
