// <auto-generated />
namespace RSC.CVSP.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddExternalIdindex : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddExternalIdindex));
        
        string IMigrationMetadata.Id
        {
            get { return "201510151650570_Add ExternalId index"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
