//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34014.
// 
#pragma warning disable 1591

namespace ChemSpider.Formats.External.CSWebService_PropertiesImport {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PropertiesSoap", Namespace="http://www.chemspider.com/")]
    public partial class Properties : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback RetrieveByInChIKeyListOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Properties() {
            this.Url = global::ChemSpider.Formats.External.Properties.Settings.Default.ChemSpider_Formats_External_CSWebService_PropertiesImport_Properties;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event RetrieveByInChIKeyListCompletedEventHandler RetrieveByInChIKeyListCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.chemspider.com/RetrieveByInChIKeyList", RequestNamespace="http://www.chemspider.com/", ResponseNamespace="http://www.chemspider.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public PropertiesInfo[] RetrieveByInChIKeyList(string[] inchi_keys, string token) {
            object[] results = this.Invoke("RetrieveByInChIKeyList", new object[] {
                        inchi_keys,
                        token});
            return ((PropertiesInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void RetrieveByInChIKeyListAsync(string[] inchi_keys, string token) {
            this.RetrieveByInChIKeyListAsync(inchi_keys, token, null);
        }
        
        /// <remarks/>
        public void RetrieveByInChIKeyListAsync(string[] inchi_keys, string token, object userState) {
            if ((this.RetrieveByInChIKeyListOperationCompleted == null)) {
                this.RetrieveByInChIKeyListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetrieveByInChIKeyListOperationCompleted);
            }
            this.InvokeAsync("RetrieveByInChIKeyList", new object[] {
                        inchi_keys,
                        token}, this.RetrieveByInChIKeyListOperationCompleted, userState);
        }
        
        private void OnRetrieveByInChIKeyListOperationCompleted(object arg) {
            if ((this.RetrieveByInChIKeyListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RetrieveByInChIKeyListCompleted(this, new RetrieveByInChIKeyListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.chemspider.com/")]
    public partial class PropertiesInfo {
        
        private int cSIDField;
        
        private string inChIKeyField;
        
        private System.Nullable<double> aLogPField;
        
        private System.Nullable<double> xLogPField;
        
        private System.Nullable<double> averageMassField;
        
        private System.Nullable<double> densityField;
        
        private System.Nullable<double> densityErrorField;
        
        private System.Nullable<double> indexOfRefractionField;
        
        private System.Nullable<double> indexOfRefractionErrorField;
        
        private System.Nullable<double> molarRefactivityField;
        
        private System.Nullable<double> molarRefactivityErrorField;
        
        private System.Nullable<double> molarVolumeField;
        
        private System.Nullable<double> molarVolumeErrorField;
        
        private System.Nullable<double> monoisotopicMassField;
        
        private System.Nullable<double> nominalMassField;
        
        private System.Nullable<double> parachorField;
        
        private System.Nullable<double> parachorErrorField;
        
        private System.Nullable<double> polarizabilityField;
        
        private System.Nullable<double> polarizabilityErrorField;
        
        private System.Nullable<double> surfaceTensionField;
        
        private System.Nullable<double> surfaceTensionErrorField;
        
        private System.Nullable<double> fpField;
        
        private System.Nullable<double> fPErrorField;
        
        private System.Nullable<double> enthalpyField;
        
        private System.Nullable<double> enthalpyErrorField;
        
        private System.Nullable<double> bpField;
        
        private System.Nullable<double> bPErrorField;
        
        private System.Nullable<double> vpField;
        
        private System.Nullable<double> vPErrorField;
        
        private System.Nullable<double> logPField;
        
        private System.Nullable<double> logPErrorField;
        
        private System.Nullable<double> ruleOf5Field;
        
        private System.Nullable<double> ruleOf5HDonorsField;
        
        private System.Nullable<double> ruleOf5HAcceptorsField;
        
        private System.Nullable<double> ruleOf5FRBField;
        
        private System.Nullable<double> ruleOf5MWField;
        
        private System.Nullable<double> ruleOf5PSAField;
        
        private System.Nullable<double> logD1Field;
        
        private System.Nullable<double> logD2Field;
        
        private System.Nullable<double> bCF1Field;
        
        private System.Nullable<double> bCF2Field;
        
        private System.Nullable<double> kOC1Field;
        
        private System.Nullable<double> kOC2Field;
        
        /// <remarks/>
        public int CSID {
            get {
                return this.cSIDField;
            }
            set {
                this.cSIDField = value;
            }
        }
        
        /// <remarks/>
        public string InChIKey {
            get {
                return this.inChIKeyField;
            }
            set {
                this.inChIKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> ALogP {
            get {
                return this.aLogPField;
            }
            set {
                this.aLogPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> XLogP {
            get {
                return this.xLogPField;
            }
            set {
                this.xLogPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> AverageMass {
            get {
                return this.averageMassField;
            }
            set {
                this.averageMassField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> Density {
            get {
                return this.densityField;
            }
            set {
                this.densityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> DensityError {
            get {
                return this.densityErrorField;
            }
            set {
                this.densityErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> IndexOfRefraction {
            get {
                return this.indexOfRefractionField;
            }
            set {
                this.indexOfRefractionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> IndexOfRefractionError {
            get {
                return this.indexOfRefractionErrorField;
            }
            set {
                this.indexOfRefractionErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> MolarRefactivity {
            get {
                return this.molarRefactivityField;
            }
            set {
                this.molarRefactivityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> MolarRefactivityError {
            get {
                return this.molarRefactivityErrorField;
            }
            set {
                this.molarRefactivityErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> MolarVolume {
            get {
                return this.molarVolumeField;
            }
            set {
                this.molarVolumeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> MolarVolumeError {
            get {
                return this.molarVolumeErrorField;
            }
            set {
                this.molarVolumeErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> MonoisotopicMass {
            get {
                return this.monoisotopicMassField;
            }
            set {
                this.monoisotopicMassField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> NominalMass {
            get {
                return this.nominalMassField;
            }
            set {
                this.nominalMassField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> Parachor {
            get {
                return this.parachorField;
            }
            set {
                this.parachorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> ParachorError {
            get {
                return this.parachorErrorField;
            }
            set {
                this.parachorErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> Polarizability {
            get {
                return this.polarizabilityField;
            }
            set {
                this.polarizabilityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> PolarizabilityError {
            get {
                return this.polarizabilityErrorField;
            }
            set {
                this.polarizabilityErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> SurfaceTension {
            get {
                return this.surfaceTensionField;
            }
            set {
                this.surfaceTensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> SurfaceTensionError {
            get {
                return this.surfaceTensionErrorField;
            }
            set {
                this.surfaceTensionErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> FP {
            get {
                return this.fpField;
            }
            set {
                this.fpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> FPError {
            get {
                return this.fPErrorField;
            }
            set {
                this.fPErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> Enthalpy {
            get {
                return this.enthalpyField;
            }
            set {
                this.enthalpyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> EnthalpyError {
            get {
                return this.enthalpyErrorField;
            }
            set {
                this.enthalpyErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> BP {
            get {
                return this.bpField;
            }
            set {
                this.bpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> BPError {
            get {
                return this.bPErrorField;
            }
            set {
                this.bPErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> VP {
            get {
                return this.vpField;
            }
            set {
                this.vpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> VPError {
            get {
                return this.vPErrorField;
            }
            set {
                this.vPErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> LogP {
            get {
                return this.logPField;
            }
            set {
                this.logPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> LogPError {
            get {
                return this.logPErrorField;
            }
            set {
                this.logPErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> RuleOf5 {
            get {
                return this.ruleOf5Field;
            }
            set {
                this.ruleOf5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> RuleOf5HDonors {
            get {
                return this.ruleOf5HDonorsField;
            }
            set {
                this.ruleOf5HDonorsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> RuleOf5HAcceptors {
            get {
                return this.ruleOf5HAcceptorsField;
            }
            set {
                this.ruleOf5HAcceptorsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> RuleOf5FRB {
            get {
                return this.ruleOf5FRBField;
            }
            set {
                this.ruleOf5FRBField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> RuleOf5MW {
            get {
                return this.ruleOf5MWField;
            }
            set {
                this.ruleOf5MWField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> RuleOf5PSA {
            get {
                return this.ruleOf5PSAField;
            }
            set {
                this.ruleOf5PSAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> LogD1 {
            get {
                return this.logD1Field;
            }
            set {
                this.logD1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> LogD2 {
            get {
                return this.logD2Field;
            }
            set {
                this.logD2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> BCF1 {
            get {
                return this.bCF1Field;
            }
            set {
                this.bCF1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> BCF2 {
            get {
                return this.bCF2Field;
            }
            set {
                this.bCF2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> KOC1 {
            get {
                return this.kOC1Field;
            }
            set {
                this.kOC1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> KOC2 {
            get {
                return this.kOC2Field;
            }
            set {
                this.kOC2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void RetrieveByInChIKeyListCompletedEventHandler(object sender, RetrieveByInChIKeyListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RetrieveByInChIKeyListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RetrieveByInChIKeyListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PropertiesInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PropertiesInfo[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591