//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34209.
// 
#pragma warning disable 1591

namespace RSC.CVSP.Compounds.com.chemspider.www.MassSpecAPI {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MassSpecAPISoap", Namespace="http://www.chemspider.com/")]
    public partial class MassSpecAPI : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetDatabasesOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchByMassOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchByMass2OperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchByFormulaOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchByFormula2OperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRecordMolOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCompressedRecordsSdfOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRecordsSdfOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetExtendedCompoundInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetExtendedCompoundInfoArrayOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetExtendedMolCompoundInfoArrayOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchByMassAsync1OperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchByMassAsyncOrderedOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchByFormulaAsync1OperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchByFormulaAsyncOrderedOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MassSpecAPI() {
            this.Url = global::RSC.CVSP.Compounds.Properties.Settings.Default.ChemValidatorLib_com_chemspider_www_MassSpecAPI_MassSpecAPI;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetDatabasesCompletedEventHandler GetDatabasesCompleted;
        
        /// <remarks/>
        public event SearchByMassCompletedEventHandler SearchByMassCompleted;
        
        /// <remarks/>
        public event SearchByMass2CompletedEventHandler SearchByMass2Completed;
        
        /// <remarks/>
        public event SearchByFormulaCompletedEventHandler SearchByFormulaCompleted;
        
        /// <remarks/>
        public event SearchByFormula2CompletedEventHandler SearchByFormula2Completed;
        
        /// <remarks/>
        public event GetRecordMolCompletedEventHandler GetRecordMolCompleted;
        
        /// <remarks/>
        public event GetCompressedRecordsSdfCompletedEventHandler GetCompressedRecordsSdfCompleted;
        
        /// <remarks/>
        public event GetRecordsSdfCompletedEventHandler GetRecordsSdfCompleted;
        
        /// <remarks/>
        public event GetExtendedCompoundInfoCompletedEventHandler GetExtendedCompoundInfoCompleted;
        
        /// <remarks/>
        public event GetExtendedCompoundInfoArrayCompletedEventHandler GetExtendedCompoundInfoArrayCompleted;
        
        /// <remarks/>
        public event GetExtendedMolCompoundInfoArrayCompletedEventHandler GetExtendedMolCompoundInfoArrayCompleted;
        
        /// <remarks/>
        public event SearchByMassAsync1CompletedEventHandler SearchByMassAsync1Completed;
        
        /// <remarks/>
        public event SearchByMassAsyncOrderedCompletedEventHandler SearchByMassAsyncOrderedCompleted;
        
        /// <remarks/>
        public event SearchByFormulaAsync1CompletedEventHandler SearchByFormulaAsync1Completed;
        
        /// <remarks/>
        public event SearchByFormulaAsyncOrderedCompletedEventHandler SearchByFormulaAsyncOrderedCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.chemspider.com/GetDatabases", RequestNamespace="http://www.chemspider.com/", ResponseNamespace="http://www.chemspider.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetDatabases() {
            object[] results = this.Invoke("GetDatabases", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetDatabasesAsync() {
            this.GetDatabasesAsync(null);
        }
        
        /// <remarks/>
        public void GetDatabasesAsync(object userState) {
            if ((this.GetDatabasesOperationCompleted == null)) {
                this.GetDatabasesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDatabasesOperationCompleted);
            }
            this.InvokeAsync("GetDatabases", new object[0], this.GetDatabasesOperationCompleted, userState);
        }
        
        private void OnGetDatabasesOperationCompleted(object arg) {
            if ((this.GetDatabasesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDatabasesCompleted(this, new GetDatabasesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.chemspider.com/SearchByMass", RequestNamespace="http://www.chemspider.com/", ResponseNamespace="http://www.chemspider.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] SearchByMass(double mass, double range, string[] dbs) {
            object[] results = this.Invoke("SearchByMass", new object[] {
                        mass,
                        range,
                        dbs});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void SearchByMassAsync(double mass, double range, string[] dbs) {
            this.SearchByMassAsync(mass, range, dbs, null);
        }
        
        /// <remarks/>
        public void SearchByMassAsync(double mass, double range, string[] dbs, object userState) {
            if ((this.SearchByMassOperationCompleted == null)) {
                this.SearchByMassOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchByMassOperationCompleted);
            }
            this.InvokeAsync("SearchByMass", new object[] {
                        mass,
                        range,
                        dbs}, this.SearchByMassOperationCompleted, userState);
        }
        
        private void OnSearchByMassOperationCompleted(object arg) {
            if ((this.SearchByMassCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchByMassCompleted(this, new SearchByMassCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.chemspider.com/SearchByMass2", RequestNamespace="http://www.chemspider.com/", ResponseNamespace="http://www.chemspider.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] SearchByMass2(double mass, double range) {
            object[] results = this.Invoke("SearchByMass2", new object[] {
                        mass,
                        range});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void SearchByMass2Async(double mass, double range) {
            this.SearchByMass2Async(mass, range, null);
        }
        
        /// <remarks/>
        public void SearchByMass2Async(double mass, double range, object userState) {
            if ((this.SearchByMass2OperationCompleted == null)) {
                this.SearchByMass2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchByMass2OperationCompleted);
            }
            this.InvokeAsync("SearchByMass2", new object[] {
                        mass,
                        range}, this.SearchByMass2OperationCompleted, userState);
        }
        
        private void OnSearchByMass2OperationCompleted(object arg) {
            if ((this.SearchByMass2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchByMass2Completed(this, new SearchByMass2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.chemspider.com/SearchByFormula", RequestNamespace="http://www.chemspider.com/", ResponseNamespace="http://www.chemspider.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] SearchByFormula(string formula, string[] dbs) {
            object[] results = this.Invoke("SearchByFormula", new object[] {
                        formula,
                        dbs});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void SearchByFormulaAsync(string formula, string[] dbs) {
            this.SearchByFormulaAsync(formula, dbs, null);
        }
        
        /// <remarks/>
        public void SearchByFormulaAsync(string formula, string[] dbs, object userState) {
            if ((this.SearchByFormulaOperationCompleted == null)) {
                this.SearchByFormulaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchByFormulaOperationCompleted);
            }
            this.InvokeAsync("SearchByFormula", new object[] {
                        formula,
                        dbs}, this.SearchByFormulaOperationCompleted, userState);
        }
        
        private void OnSearchByFormulaOperationCompleted(object arg) {
            if ((this.SearchByFormulaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchByFormulaCompleted(this, new SearchByFormulaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.chemspider.com/SearchByFormula2", RequestNamespace="http://www.chemspider.com/", ResponseNamespace="http://www.chemspider.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] SearchByFormula2(string formula) {
            object[] results = this.Invoke("SearchByFormula2", new object[] {
                        formula});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void SearchByFormula2Async(string formula) {
            this.SearchByFormula2Async(formula, null);
        }
        
        /// <remarks/>
        public void SearchByFormula2Async(string formula, object userState) {
            if ((this.SearchByFormula2OperationCompleted == null)) {
                this.SearchByFormula2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchByFormula2OperationCompleted);
            }
            this.InvokeAsync("SearchByFormula2", new object[] {
                        formula}, this.SearchByFormula2OperationCompleted, userState);
        }
        
        private void OnSearchByFormula2OperationCompleted(object arg) {
            if ((this.SearchByFormula2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchByFormula2Completed(this, new SearchByFormula2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.chemspider.com/GetRecordMol", RequestNamespace="http://www.chemspider.com/", ResponseNamespace="http://www.chemspider.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetRecordMol(string csid, bool calc3d, string token) {
            object[] results = this.Invoke("GetRecordMol", new object[] {
                        csid,
                        calc3d,
                        token});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetRecordMolAsync(string csid, bool calc3d, string token) {
            this.GetRecordMolAsync(csid, calc3d, token, null);
        }
        
        /// <remarks/>
        public void GetRecordMolAsync(string csid, bool calc3d, string token, object userState) {
            if ((this.GetRecordMolOperationCompleted == null)) {
                this.GetRecordMolOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRecordMolOperationCompleted);
            }
            this.InvokeAsync("GetRecordMol", new object[] {
                        csid,
                        calc3d,
                        token}, this.GetRecordMolOperationCompleted, userState);
        }
        
        private void OnGetRecordMolOperationCompleted(object arg) {
            if ((this.GetRecordMolCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRecordMolCompleted(this, new GetRecordMolCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.chemspider.com/GetCompressedRecordsSdf", RequestNamespace="http://www.chemspider.com/", ResponseNamespace="http://www.chemspider.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GetCompressedRecordsSdf(string rid, string token, ECompression eComp) {
            object[] results = this.Invoke("GetCompressedRecordsSdf", new object[] {
                        rid,
                        token,
                        eComp});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCompressedRecordsSdfAsync(string rid, string token, ECompression eComp) {
            this.GetCompressedRecordsSdfAsync(rid, token, eComp, null);
        }
        
        /// <remarks/>
        public void GetCompressedRecordsSdfAsync(string rid, string token, ECompression eComp, object userState) {
            if ((this.GetCompressedRecordsSdfOperationCompleted == null)) {
                this.GetCompressedRecordsSdfOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCompressedRecordsSdfOperationCompleted);
            }
            this.InvokeAsync("GetCompressedRecordsSdf", new object[] {
                        rid,
                        token,
                        eComp}, this.GetCompressedRecordsSdfOperationCompleted, userState);
        }
        
        private void OnGetCompressedRecordsSdfOperationCompleted(object arg) {
            if ((this.GetCompressedRecordsSdfCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCompressedRecordsSdfCompleted(this, new GetCompressedRecordsSdfCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.chemspider.com/GetRecordsSdf", RequestNamespace="http://www.chemspider.com/", ResponseNamespace="http://www.chemspider.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetRecordsSdf(string rid, string token) {
            object[] results = this.Invoke("GetRecordsSdf", new object[] {
                        rid,
                        token});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetRecordsSdfAsync(string rid, string token) {
            this.GetRecordsSdfAsync(rid, token, null);
        }
        
        /// <remarks/>
        public void GetRecordsSdfAsync(string rid, string token, object userState) {
            if ((this.GetRecordsSdfOperationCompleted == null)) {
                this.GetRecordsSdfOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRecordsSdfOperationCompleted);
            }
            this.InvokeAsync("GetRecordsSdf", new object[] {
                        rid,
                        token}, this.GetRecordsSdfOperationCompleted, userState);
        }
        
        private void OnGetRecordsSdfOperationCompleted(object arg) {
            if ((this.GetRecordsSdfCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRecordsSdfCompleted(this, new GetRecordsSdfCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.chemspider.com/GetExtendedCompoundInfo", RequestNamespace="http://www.chemspider.com/", ResponseNamespace="http://www.chemspider.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ExtendedCompoundInfo GetExtendedCompoundInfo(int CSID, string token) {
            object[] results = this.Invoke("GetExtendedCompoundInfo", new object[] {
                        CSID,
                        token});
            return ((ExtendedCompoundInfo)(results[0]));
        }
        
        /// <remarks/>
        public void GetExtendedCompoundInfoAsync(int CSID, string token) {
            this.GetExtendedCompoundInfoAsync(CSID, token, null);
        }
        
        /// <remarks/>
        public void GetExtendedCompoundInfoAsync(int CSID, string token, object userState) {
            if ((this.GetExtendedCompoundInfoOperationCompleted == null)) {
                this.GetExtendedCompoundInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetExtendedCompoundInfoOperationCompleted);
            }
            this.InvokeAsync("GetExtendedCompoundInfo", new object[] {
                        CSID,
                        token}, this.GetExtendedCompoundInfoOperationCompleted, userState);
        }
        
        private void OnGetExtendedCompoundInfoOperationCompleted(object arg) {
            if ((this.GetExtendedCompoundInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetExtendedCompoundInfoCompleted(this, new GetExtendedCompoundInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.chemspider.com/GetExtendedCompoundInfoArray", RequestNamespace="http://www.chemspider.com/", ResponseNamespace="http://www.chemspider.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ExtendedCompoundInfo[] GetExtendedCompoundInfoArray(int[] CSIDs, string token) {
            object[] results = this.Invoke("GetExtendedCompoundInfoArray", new object[] {
                        CSIDs,
                        token});
            return ((ExtendedCompoundInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetExtendedCompoundInfoArrayAsync(int[] CSIDs, string token) {
            this.GetExtendedCompoundInfoArrayAsync(CSIDs, token, null);
        }
        
        /// <remarks/>
        public void GetExtendedCompoundInfoArrayAsync(int[] CSIDs, string token, object userState) {
            if ((this.GetExtendedCompoundInfoArrayOperationCompleted == null)) {
                this.GetExtendedCompoundInfoArrayOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetExtendedCompoundInfoArrayOperationCompleted);
            }
            this.InvokeAsync("GetExtendedCompoundInfoArray", new object[] {
                        CSIDs,
                        token}, this.GetExtendedCompoundInfoArrayOperationCompleted, userState);
        }
        
        private void OnGetExtendedCompoundInfoArrayOperationCompleted(object arg) {
            if ((this.GetExtendedCompoundInfoArrayCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetExtendedCompoundInfoArrayCompleted(this, new GetExtendedCompoundInfoArrayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.chemspider.com/GetExtendedMolCompoundInfoArray", RequestNamespace="http://www.chemspider.com/", ResponseNamespace="http://www.chemspider.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ExtendedMolCompoundInfo[] GetExtendedMolCompoundInfoArray(int[] CSIDs, EMolType eMolType, bool includeReferenceCounts, bool includeExternalReferences, string token) {
            object[] results = this.Invoke("GetExtendedMolCompoundInfoArray", new object[] {
                        CSIDs,
                        eMolType,
                        includeReferenceCounts,
                        includeExternalReferences,
                        token});
            return ((ExtendedMolCompoundInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetExtendedMolCompoundInfoArrayAsync(int[] CSIDs, EMolType eMolType, bool includeReferenceCounts, bool includeExternalReferences, string token) {
            this.GetExtendedMolCompoundInfoArrayAsync(CSIDs, eMolType, includeReferenceCounts, includeExternalReferences, token, null);
        }
        
        /// <remarks/>
        public void GetExtendedMolCompoundInfoArrayAsync(int[] CSIDs, EMolType eMolType, bool includeReferenceCounts, bool includeExternalReferences, string token, object userState) {
            if ((this.GetExtendedMolCompoundInfoArrayOperationCompleted == null)) {
                this.GetExtendedMolCompoundInfoArrayOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetExtendedMolCompoundInfoArrayOperationCompleted);
            }
            this.InvokeAsync("GetExtendedMolCompoundInfoArray", new object[] {
                        CSIDs,
                        eMolType,
                        includeReferenceCounts,
                        includeExternalReferences,
                        token}, this.GetExtendedMolCompoundInfoArrayOperationCompleted, userState);
        }
        
        private void OnGetExtendedMolCompoundInfoArrayOperationCompleted(object arg) {
            if ((this.GetExtendedMolCompoundInfoArrayCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetExtendedMolCompoundInfoArrayCompleted(this, new GetExtendedMolCompoundInfoArrayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute(MessageName="SearchByMassAsync1")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.chemspider.com/SearchByMassAsync", RequestElementName="SearchByMassAsync", RequestNamespace="http://www.chemspider.com/", ResponseElementName="SearchByMassAsyncResponse", ResponseNamespace="http://www.chemspider.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("SearchByMassAsyncResult")]
        public string SearchByMassAsync(double mass, double range, string[] dbs, string token) {
            object[] results = this.Invoke("SearchByMassAsync1", new object[] {
                        mass,
                        range,
                        dbs,
                        token});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SearchByMassAsync1Async(double mass, double range, string[] dbs, string token) {
            this.SearchByMassAsync1Async(mass, range, dbs, token, null);
        }
        
        /// <remarks/>
        public void SearchByMassAsync1Async(double mass, double range, string[] dbs, string token, object userState) {
            if ((this.SearchByMassAsync1OperationCompleted == null)) {
                this.SearchByMassAsync1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchByMassAsync1OperationCompleted);
            }
            this.InvokeAsync("SearchByMassAsync1", new object[] {
                        mass,
                        range,
                        dbs,
                        token}, this.SearchByMassAsync1OperationCompleted, userState);
        }
        
        private void OnSearchByMassAsync1OperationCompleted(object arg) {
            if ((this.SearchByMassAsync1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchByMassAsync1Completed(this, new SearchByMassAsync1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.chemspider.com/SearchByMassAsyncOrdered", RequestNamespace="http://www.chemspider.com/", ResponseNamespace="http://www.chemspider.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SearchByMassAsyncOrdered(double mass, double range, string[] dbs, EOrderBy orderBy, EOrderDirection orderDirection, string token) {
            object[] results = this.Invoke("SearchByMassAsyncOrdered", new object[] {
                        mass,
                        range,
                        dbs,
                        orderBy,
                        orderDirection,
                        token});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SearchByMassAsyncOrderedAsync(double mass, double range, string[] dbs, EOrderBy orderBy, EOrderDirection orderDirection, string token) {
            this.SearchByMassAsyncOrderedAsync(mass, range, dbs, orderBy, orderDirection, token, null);
        }
        
        /// <remarks/>
        public void SearchByMassAsyncOrderedAsync(double mass, double range, string[] dbs, EOrderBy orderBy, EOrderDirection orderDirection, string token, object userState) {
            if ((this.SearchByMassAsyncOrderedOperationCompleted == null)) {
                this.SearchByMassAsyncOrderedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchByMassAsyncOrderedOperationCompleted);
            }
            this.InvokeAsync("SearchByMassAsyncOrdered", new object[] {
                        mass,
                        range,
                        dbs,
                        orderBy,
                        orderDirection,
                        token}, this.SearchByMassAsyncOrderedOperationCompleted, userState);
        }
        
        private void OnSearchByMassAsyncOrderedOperationCompleted(object arg) {
            if ((this.SearchByMassAsyncOrderedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchByMassAsyncOrderedCompleted(this, new SearchByMassAsyncOrderedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute(MessageName="SearchByFormulaAsync1")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.chemspider.com/SearchByFormulaAsync", RequestElementName="SearchByFormulaAsync", RequestNamespace="http://www.chemspider.com/", ResponseElementName="SearchByFormulaAsyncResponse", ResponseNamespace="http://www.chemspider.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("SearchByFormulaAsyncResult")]
        public string SearchByFormulaAsync(string formula, string[] dbs, string token) {
            object[] results = this.Invoke("SearchByFormulaAsync1", new object[] {
                        formula,
                        dbs,
                        token});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SearchByFormulaAsync1Async(string formula, string[] dbs, string token) {
            this.SearchByFormulaAsync1Async(formula, dbs, token, null);
        }
        
        /// <remarks/>
        public void SearchByFormulaAsync1Async(string formula, string[] dbs, string token, object userState) {
            if ((this.SearchByFormulaAsync1OperationCompleted == null)) {
                this.SearchByFormulaAsync1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchByFormulaAsync1OperationCompleted);
            }
            this.InvokeAsync("SearchByFormulaAsync1", new object[] {
                        formula,
                        dbs,
                        token}, this.SearchByFormulaAsync1OperationCompleted, userState);
        }
        
        private void OnSearchByFormulaAsync1OperationCompleted(object arg) {
            if ((this.SearchByFormulaAsync1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchByFormulaAsync1Completed(this, new SearchByFormulaAsync1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.chemspider.com/SearchByFormulaAsyncOrdered", RequestNamespace="http://www.chemspider.com/", ResponseNamespace="http://www.chemspider.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SearchByFormulaAsyncOrdered(string formula, string[] dbs, EOrderBy orderBy, EOrderDirection orderDirection, string token) {
            object[] results = this.Invoke("SearchByFormulaAsyncOrdered", new object[] {
                        formula,
                        dbs,
                        orderBy,
                        orderDirection,
                        token});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SearchByFormulaAsyncOrderedAsync(string formula, string[] dbs, EOrderBy orderBy, EOrderDirection orderDirection, string token) {
            this.SearchByFormulaAsyncOrderedAsync(formula, dbs, orderBy, orderDirection, token, null);
        }
        
        /// <remarks/>
        public void SearchByFormulaAsyncOrderedAsync(string formula, string[] dbs, EOrderBy orderBy, EOrderDirection orderDirection, string token, object userState) {
            if ((this.SearchByFormulaAsyncOrderedOperationCompleted == null)) {
                this.SearchByFormulaAsyncOrderedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchByFormulaAsyncOrderedOperationCompleted);
            }
            this.InvokeAsync("SearchByFormulaAsyncOrdered", new object[] {
                        formula,
                        dbs,
                        orderBy,
                        orderDirection,
                        token}, this.SearchByFormulaAsyncOrderedOperationCompleted, userState);
        }
        
        private void OnSearchByFormulaAsyncOrderedOperationCompleted(object arg) {
            if ((this.SearchByFormulaAsyncOrderedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchByFormulaAsyncOrderedCompleted(this, new SearchByFormulaAsyncOrderedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.chemspider.com/")]
    public enum ECompression {
        
        /// <remarks/>
        eGzip,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.chemspider.com/")]
    public partial class ExtendedCompoundInfo {
        
        private int cSIDField;
        
        private string mfField;
        
        private string sMILESField;
        
        private string inChIField;
        
        private string inChIKeyField;
        
        private double averageMassField;
        
        private double molecularWeightField;
        
        private double monoisotopicMassField;
        
        private double nominalMassField;
        
        private double aLogPField;
        
        private double xLogPField;
        
        private string commonNameField;
        
        /// <remarks/>
        public int CSID {
            get {
                return this.cSIDField;
            }
            set {
                this.cSIDField = value;
            }
        }
        
        /// <remarks/>
        public string MF {
            get {
                return this.mfField;
            }
            set {
                this.mfField = value;
            }
        }
        
        /// <remarks/>
        public string SMILES {
            get {
                return this.sMILESField;
            }
            set {
                this.sMILESField = value;
            }
        }
        
        /// <remarks/>
        public string InChI {
            get {
                return this.inChIField;
            }
            set {
                this.inChIField = value;
            }
        }
        
        /// <remarks/>
        public string InChIKey {
            get {
                return this.inChIKeyField;
            }
            set {
                this.inChIKeyField = value;
            }
        }
        
        /// <remarks/>
        public double AverageMass {
            get {
                return this.averageMassField;
            }
            set {
                this.averageMassField = value;
            }
        }
        
        /// <remarks/>
        public double MolecularWeight {
            get {
                return this.molecularWeightField;
            }
            set {
                this.molecularWeightField = value;
            }
        }
        
        /// <remarks/>
        public double MonoisotopicMass {
            get {
                return this.monoisotopicMassField;
            }
            set {
                this.monoisotopicMassField = value;
            }
        }
        
        /// <remarks/>
        public double NominalMass {
            get {
                return this.nominalMassField;
            }
            set {
                this.nominalMassField = value;
            }
        }
        
        /// <remarks/>
        public double ALogP {
            get {
                return this.aLogPField;
            }
            set {
                this.aLogPField = value;
            }
        }
        
        /// <remarks/>
        public double XLogP {
            get {
                return this.xLogPField;
            }
            set {
                this.xLogPField = value;
            }
        }
        
        /// <remarks/>
        public string CommonName {
            get {
                return this.commonNameField;
            }
            set {
                this.commonNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.chemspider.com/")]
    public partial class ExtRef {
        
        private int cSIDField;
        
        private string ds_nameField;
        
        private string ds_urlField;
        
        private string ext_idField;
        
        private string ext_urlField;
        
        /// <remarks/>
        public int CSID {
            get {
                return this.cSIDField;
            }
            set {
                this.cSIDField = value;
            }
        }
        
        /// <remarks/>
        public string ds_name {
            get {
                return this.ds_nameField;
            }
            set {
                this.ds_nameField = value;
            }
        }
        
        /// <remarks/>
        public string ds_url {
            get {
                return this.ds_urlField;
            }
            set {
                this.ds_urlField = value;
            }
        }
        
        /// <remarks/>
        public string ext_id {
            get {
                return this.ext_idField;
            }
            set {
                this.ext_idField = value;
            }
        }
        
        /// <remarks/>
        public string ext_url {
            get {
                return this.ext_urlField;
            }
            set {
                this.ext_urlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.chemspider.com/")]
    public partial class ExtendedMolCompoundInfo {
        
        private int cSIDField;
        
        private string mOL2dField;
        
        private string mOL3dField;
        
        private int referenceCountField;
        
        private int dataSourceCountField;
        
        private int pubMedCountField;
        
        private int rSCCountField;
        
        private string mfField;
        
        private string sMILESField;
        
        private string inChIField;
        
        private string inChIKeyField;
        
        private double averageMassField;
        
        private double molecularWeightField;
        
        private double monoisotopicMassField;
        
        private double nominalMassField;
        
        private double aLogPField;
        
        private double xLogPField;
        
        private string commonNameField;
        
        private ExtRef[] externalReferencesField;
        
        /// <remarks/>
        public int CSID {
            get {
                return this.cSIDField;
            }
            set {
                this.cSIDField = value;
            }
        }
        
        /// <remarks/>
        public string MOL2d {
            get {
                return this.mOL2dField;
            }
            set {
                this.mOL2dField = value;
            }
        }
        
        /// <remarks/>
        public string MOL3d {
            get {
                return this.mOL3dField;
            }
            set {
                this.mOL3dField = value;
            }
        }
        
        /// <remarks/>
        public int ReferenceCount {
            get {
                return this.referenceCountField;
            }
            set {
                this.referenceCountField = value;
            }
        }
        
        /// <remarks/>
        public int DataSourceCount {
            get {
                return this.dataSourceCountField;
            }
            set {
                this.dataSourceCountField = value;
            }
        }
        
        /// <remarks/>
        public int PubMedCount {
            get {
                return this.pubMedCountField;
            }
            set {
                this.pubMedCountField = value;
            }
        }
        
        /// <remarks/>
        public int RSCCount {
            get {
                return this.rSCCountField;
            }
            set {
                this.rSCCountField = value;
            }
        }
        
        /// <remarks/>
        public string MF {
            get {
                return this.mfField;
            }
            set {
                this.mfField = value;
            }
        }
        
        /// <remarks/>
        public string SMILES {
            get {
                return this.sMILESField;
            }
            set {
                this.sMILESField = value;
            }
        }
        
        /// <remarks/>
        public string InChI {
            get {
                return this.inChIField;
            }
            set {
                this.inChIField = value;
            }
        }
        
        /// <remarks/>
        public string InChIKey {
            get {
                return this.inChIKeyField;
            }
            set {
                this.inChIKeyField = value;
            }
        }
        
        /// <remarks/>
        public double AverageMass {
            get {
                return this.averageMassField;
            }
            set {
                this.averageMassField = value;
            }
        }
        
        /// <remarks/>
        public double MolecularWeight {
            get {
                return this.molecularWeightField;
            }
            set {
                this.molecularWeightField = value;
            }
        }
        
        /// <remarks/>
        public double MonoisotopicMass {
            get {
                return this.monoisotopicMassField;
            }
            set {
                this.monoisotopicMassField = value;
            }
        }
        
        /// <remarks/>
        public double NominalMass {
            get {
                return this.nominalMassField;
            }
            set {
                this.nominalMassField = value;
            }
        }
        
        /// <remarks/>
        public double ALogP {
            get {
                return this.aLogPField;
            }
            set {
                this.aLogPField = value;
            }
        }
        
        /// <remarks/>
        public double XLogP {
            get {
                return this.xLogPField;
            }
            set {
                this.xLogPField = value;
            }
        }
        
        /// <remarks/>
        public string CommonName {
            get {
                return this.commonNameField;
            }
            set {
                this.commonNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ExtRef[] ExternalReferences {
            get {
                return this.externalReferencesField;
            }
            set {
                this.externalReferencesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.chemspider.com/")]
    public enum EMolType {
        
        /// <remarks/>
        e2D,
        
        /// <remarks/>
        e3D,
        
        /// <remarks/>
        eBoth,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.chemspider.com/")]
    public enum EOrderBy {
        
        /// <remarks/>
        eCSID,
        
        /// <remarks/>
        eMassDefect,
        
        /// <remarks/>
        eMolecularWeight,
        
        /// <remarks/>
        eReferenceCount,
        
        /// <remarks/>
        eDataSourceCount,
        
        /// <remarks/>
        ePubMedCount,
        
        /// <remarks/>
        eRscCount,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.chemspider.com/")]
    public enum EOrderDirection {
        
        /// <remarks/>
        eAscending,
        
        /// <remarks/>
        eDescending,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetDatabasesCompletedEventHandler(object sender, GetDatabasesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDatabasesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDatabasesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void SearchByMassCompletedEventHandler(object sender, SearchByMassCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchByMassCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchByMassCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void SearchByMass2CompletedEventHandler(object sender, SearchByMass2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchByMass2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchByMass2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void SearchByFormulaCompletedEventHandler(object sender, SearchByFormulaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchByFormulaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchByFormulaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void SearchByFormula2CompletedEventHandler(object sender, SearchByFormula2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchByFormula2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchByFormula2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetRecordMolCompletedEventHandler(object sender, GetRecordMolCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRecordMolCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRecordMolCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetCompressedRecordsSdfCompletedEventHandler(object sender, GetCompressedRecordsSdfCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCompressedRecordsSdfCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCompressedRecordsSdfCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetRecordsSdfCompletedEventHandler(object sender, GetRecordsSdfCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRecordsSdfCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRecordsSdfCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetExtendedCompoundInfoCompletedEventHandler(object sender, GetExtendedCompoundInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetExtendedCompoundInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetExtendedCompoundInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ExtendedCompoundInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ExtendedCompoundInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetExtendedCompoundInfoArrayCompletedEventHandler(object sender, GetExtendedCompoundInfoArrayCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetExtendedCompoundInfoArrayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetExtendedCompoundInfoArrayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ExtendedCompoundInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ExtendedCompoundInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetExtendedMolCompoundInfoArrayCompletedEventHandler(object sender, GetExtendedMolCompoundInfoArrayCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetExtendedMolCompoundInfoArrayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetExtendedMolCompoundInfoArrayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ExtendedMolCompoundInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ExtendedMolCompoundInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void SearchByMassAsync1CompletedEventHandler(object sender, SearchByMassAsync1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchByMassAsync1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchByMassAsync1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void SearchByMassAsyncOrderedCompletedEventHandler(object sender, SearchByMassAsyncOrderedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchByMassAsyncOrderedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchByMassAsyncOrderedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void SearchByFormulaAsync1CompletedEventHandler(object sender, SearchByFormulaAsync1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchByFormulaAsync1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchByFormulaAsync1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void SearchByFormulaAsyncOrderedCompletedEventHandler(object sender, SearchByFormulaAsyncOrderedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchByFormulaAsyncOrderedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchByFormulaAsyncOrderedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591