//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChemSpider.Formats {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FormatsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormatsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChemSpider.Formats.FormatsResources", typeof(FormatsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled Document-1
        ///  ChemDraw11301115512D
        ///
        /// 12 13  0  0  0  0  0  0  0  0999 V2000
        ///   -0.0720   -0.3336    0.0000 B   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -0.6456    0.2593    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    0.7283   -0.1333    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    0.9550    0.6600    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -0.4190    1.0525    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    0.3813    1.2529    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MoleculeEnumeratorFragments {
            get {
                return ResourceManager.GetString("MoleculeEnumeratorFragments", resourceCulture);
            }
        }
    }
}
