//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVSPTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PartialIonizationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PartialIonizationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CVSPTests.PartialIonizationResources", typeof(PartialIonizationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  -INDIGO-02281308012D
        ///
        /// 70 78  0  0  1  0  0  0  0  0999 V2000
        ///   -1.0536   12.3306    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -0.9674   11.5101    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -0.2137   11.1746    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -1.6348   11.0252    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -1.5486   10.2047    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -2.2160    9.7198    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -2.9697   10.0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string partialIonization_amineAmide {
            get {
                return ResourceManager.GetString("partialIonization_amineAmide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mixed
        ///  -INDIGO-02211316312D
        ///
        /// 22 21  0  0  0  0  0  0  0  0999 V2000
        ///   15.8459   -9.3897    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   14.4033  -10.2226    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
        ///   15.1246   -8.9732    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
        ///   14.4033   -9.3897    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   12.9607  -10.2226    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   13.6820   -8.9733    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   12.9607   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string partialIonization_sodiumSulfateThiol {
            get {
                return ResourceManager.GetString("partialIonization_sodiumSulfateThiol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10-230
        ///  -INDIGO-02271310382D
        ///
        /// 12 12  0  0  0  0  0  0  0  0999 V2000
        ///   10.7904   -7.1872    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    9.7675   -6.5966    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
        ///    8.7446   -7.1872    0.0000 S   0  0  0  0  0  0  0  0  0  0  0  0
        ///    7.7218   -6.5966    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
        ///    8.7446   -8.3683    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
        ///    9.7675   -7.7777    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
        ///   11.8688  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string partialIonization_sulfateMethyl {
            get {
                return ResourceManager.GetString("partialIonization_sulfateMethyl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  SMMXDraw06061217052D
        ///
        /// 15 15  0  0  0  0  0  0  0  0999 V2000
        ///    7.4153   -4.9714    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    9.4576   -4.9708    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    8.4384   -4.3811    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    9.4576   -6.1523    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    7.4153   -6.1576    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    8.4409   -6.7418    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    6.3924   -4.3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string partialIonization_sulfateSulfonate {
            get {
                return ResourceManager.GetString("partialIonization_sulfateSulfonate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10-80
        ///  -INDIGO-02261322052D
        ///
        /// 12 12  0  0  0  0  0  0  0  0999 V2000
        ///   10.7904   -7.1872    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   12.8327   -7.1866    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   11.8135   -6.5969    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   12.8327   -8.3681    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   10.7904   -8.3734    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   11.8160   -8.9576    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    9.7675   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string partialIonization_sulfateThiol {
            get {
                return ResourceManager.GetString("partialIonization_sulfateThiol", resourceCulture);
            }
        }
    }
}
