//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVSPTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CVSPTests.ValidationResources", typeof(ValidationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.k.i tetracycline
        ///  -INDIGO-02211315112D
        ///
        /// 34 37  0  0  1  0  0  0  0  0999 V2000
        ///    6.8543   -6.6566    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
        ///    9.9333   -8.4294    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
        ///    6.0894   -8.7423    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
        ///    4.7984   -4.2798    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
        ///    8.9011   -4.2780    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
        ///    9.9333   -4.8762    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _20ki_tetracycline {
            get {
                return ResourceManager.GetString("_20ki_tetracycline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  Ketcher 09201311452D 1   1.00000     0.00000     0
        ///
        /// 13 12  0     1  0            999 V2000
        ///    3.2729   -3.4457    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    2.5035   -4.0047    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    2.7973   -4.9093    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    3.7484   -4.9093    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    4.0423   -4.0047    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    4.2242   -5.7334    0.0000 C   0  0  0  0  0  0  0  0  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string acidbase {
            get {
                return ResourceManager.GetString("acidbase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 910
        ///  Mrv0541 02231215062D          
        ///
        /// 33 35  0  0  1  0            999 V2000
        ///    7.9284    4.5423    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
        ///    4.5080   -4.1363    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
        ///    1.6500   -4.1363    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
        ///    4.5080    0.8138    0.0000 C   0  0  2  0  0  0  0  0  0  0  0  0
        ///    5.2886    1.0653    0.0000 C   0  0  2  0  0  0  0  0  0  0  0  0
        ///    4.5080   -0.0112    0.0000 C   0  0  1  0  0  0  0  0  0  0  0  0
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ambiguousSp3Stereo {
            get {
                return ResourceManager.GetString("ambiguousSp3Stereo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  Ketcher 11181411112D 1   1.00000     0.00000     0
        ///
        ///  7  6  0     0  0            999 V2000
        ///    1.9617    0.1284    0.0000 I   0  0  0  0  0  0  0  0  0  0  0  0
        ///    2.9714    0.6731    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    4.6846   -0.3161    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    3.8272    0.1777    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    5.1815   -1.1736    0.0000 Br  0  0  0  0  0  0  0  0  0  0  0  0
        ///    2.9865    1.6729    0.0000 C   0  0  0  0  0  0  0  0  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string badallene {
            get {
                return ResourceManager.GetString("badallene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  Ketcher 11181411452D 1   1.00000     0.00000     0
        ///
        ///  7  6  0     0  0            999 V2000
        ///    1.9617    0.1284    0.0000 I   0  0  0  0  0  0  0  0  0  0  0  0
        ///    2.9714    0.6731    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    4.6846   -0.3161    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    3.8272    0.1777    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    5.1815   -1.1736    0.0000 Br  0  0  0  0  0  0  0  0  0  0  0  0
        ///    2.9865    1.6729    0.0000 C   0  0  0  0  0  0  0  0  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string badallene2 {
            get {
                return ResourceManager.GetString("badallene2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  ACCLDraw08281311242D
        ///
        /// 20 23  0  0  1  0  0  0  0  0999 V2000
        ///    8.9392   -6.1749    0.0000 C   0  0  2  0  0  0  0  0  0  0  0  0
        ///    9.8100   -6.6820    0.0000 C   0  0  1  0  0  0  0  0  0  0  0  0
        ///    8.9392   -5.1606    0.0000 C   0  0  2  0  0  0  0  0  0  0  0  0
        ///    9.8100   -7.6962    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
        ///    8.0633   -6.6768    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   11.5516   -7.6962    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    8.4167   -5.8 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string badvalency {
            get {
                return ResourceManager.GetString("badvalency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled Document-1
        ///  ChemDraw07151510342D
        ///
        ///  3  2  0  0  0  0  0  0  0  0999 V2000
        ///   -0.6188   -0.3572    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    0.2062   -0.3572    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    0.6188    0.3572    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
        ///  1  2  1  0      
        ///  2  3  3  0      
        ///M  END.
        /// </summary>
        internal static string bentacetonitrile {
            get {
                return ResourceManager.GetString("bentacetonitrile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to benzene.cdx
        /// OpenBabel09081111092D
        ///
        ///  6  6  0  0  0  0  0  0  0  0999 V2000
        ///   21.3320  -32.2437    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   21.3320  -36.1759    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   24.7373  -38.1420    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   28.1427  -36.1759    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   28.1427  -32.2437    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   24.7373  -30.2776    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///  1  2  6  0  0  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string benzene_withQueryBonds {
            get {
                return ResourceManager.GetString("benzene_withQueryBonds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  Ketcher 04071416502D 1   1.00000     0.00000     0
        ///
        ///  8  8  0     0  0            999 V2000
        ///   -2.8750    2.5250    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -2.0090    2.0250    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -2.0090    1.0250    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -2.8750    0.5250    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -3.7410    1.0250    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -3.7410    2.0250    0.0000 C   0  0  0  0  0  0  0  0  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string benzyllithium_bonded {
            get {
                return ResourceManager.GetString("benzyllithium_bonded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  Ketcher 04081410312D 1   1.00000     0.00000     0
        ///
        ///  7  6  0     0  0            999 V2000
        ///   -2.8750    2.5250    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -2.0090    2.0250    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -2.0090    1.0250    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -2.8750    0.5250    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -3.7411    1.0250    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -3.7411    2.0250    0.0000 C   0  0  0  0  0  0  0  0  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string benzyllithium_free {
            get {
                return ResourceManager.GetString("benzyllithium_free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  Ketcher 04071416482D 1   1.00000     0.00000     0
        ///
        ///  7  6  0     0  0            999 V2000
        ///   -2.8750    2.5250    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -2.0090    2.0250    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -2.0090    1.0250    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -2.8750    0.5250    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -3.7410    1.0250    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -3.7410    2.0250    0.0000 C   0  0  0  0  0  0  0  0  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string benzyllithium_freeneutral {
            get {
                return ResourceManager.GetString("benzyllithium_freeneutral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  -INDIGO-05061306482D
        ///
        /// 22 24  0  0  0  0  0  0  0  0999 V2000
        ///   -2.7107   -0.7366    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -3.4252   -1.1491    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -3.4252   -1.9741    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -2.7107   -2.3866    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -1.9962   -1.9741    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -1.9962   -1.1491    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -1.2818   -0.7 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bondType4molecule {
            get {
                return ResourceManager.GetString("bondType4molecule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0
        ///CBDIGESTER0125130518
        ///
        ///  6  6  0  0000  0  0  0  0  0999 V2000
        ///  259.1992  -96.0000    0.0000 N   0  0  0  0  0  0  0  0  0  0  0
        ///  259.1992 -124.0508    0.0000 B   0  0  0  0  0  0  0  0  0  0  0
        ///  283.5000 -138.0508    0.0000 N   0  0  0  0  0  0  0  0  0  0  0
        ///  307.8008 -124.0508    0.0000 B   0  0  0  0  0  0  0  0  0  0  0
        ///  307.8008  -96.0000    0.0000 N   0  0  0  0  0  0  0  0  0  0  0
        ///  283.5000  -81.9492    0.0000 B   0  0  0  0  0  0  0  0  0  0  0
        ///  1  2  4  0
        ///  2  3  4  0
        ///  3  4   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string borazine_nonunique {
            get {
                return ResourceManager.GetString("borazine_nonunique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  Ketcher 12041412012D 1   1.00000     0.00000     0
        ///
        ///  5  4  0     0  0            999 V2000
        ///    6.9223   -4.4103    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    7.7019   -3.9603    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    8.4814   -4.4103    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    8.9314   -5.1897    0.0000 Cl  0  0  0  0  0  0  0  0  0  0  0  0
        ///    9.5678   -3.6967    0.0000 I   0  0  0  0  0  0  0  0  0  0  0  0
        ///  1  2  1  0     0  0
        ///  2  3  2  3     0  0
        ///  3  4  1  0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bromoiodopropene_crossedandwavy {
            get {
                return ResourceManager.GetString("bromoiodopropene_crossedandwavy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  Ketcher 12041409172D 1   1.00000     0.00000     0
        ///
        ///  5  4  0     0  0            999 V2000
        ///    7.6910   -4.9000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    8.5571   -4.4000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    9.4231   -4.9000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    9.9231   -5.7660    0.0000 Cl  0  0  0  0  0  0  0  0  0  0  0  0
        ///   10.6302   -4.1071    0.0000 I   0  0  0  0  0  0  0  0  0  0  0  0
        ///  1  2  1  0     0  0
        ///  2  3  2  3     0  0
        ///  3  4  1  0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bromoiodopropene_crossedonly {
            get {
                return ResourceManager.GetString("bromoiodopropene_crossedonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  Ketcher 12041409212D 1   1.00000     0.00000     0
        ///
        ///  5  4  0     0  0            999 V2000
        ///    6.9222   -4.4102    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    7.7017   -3.9602    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    8.4812   -4.4102    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    8.9312   -5.1896    0.0000 Cl  0  0  0  0  0  0  0  0  0  0  0  0
        ///    9.5676   -3.6966    0.0000 I   0  0  0  0  0  0  0  0  0  0  0  0
        ///  1  2  1  0     0  0
        ///  2  3  2  0     0  0
        ///  3  4  1  0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bromoiodopropene_flat {
            get {
                return ResourceManager.GetString("bromoiodopropene_flat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled Document-1
        ///  ChemDraw07011512192D
        ///
        ///  5  4  0  0  0  0  0  0  0  0999 V2000
        ///   -1.0313    0.7145    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -0.2062    0.7145    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    0.2062    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    1.0313    0.0000    0.0000 I   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -0.2062   -0.7145    0.0000 Br  0  0  0  0  0  0  0  0  0  0  0  0
        ///  1  2  1  0      
        ///  2  3  2  0      
        ///  3  4  1  0      
        ///  3  5  1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bromoiodopropene_wavy {
            get {
                return ResourceManager.GetString("bromoiodopropene_wavy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  Mrv0541 04051115152D          
        ///
        /// 21 22  0  0  0  0            999 V2000
        ///    1.0745    0.5735    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -1.6096   -3.6346    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    1.8360    3.5334    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -1.4602   -2.2135    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -0.6398   -2.2997    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -0.3042   -3.0534    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    1.8 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CHEMBL12760_doublebondadjacenttoupbond {
            get {
                return ResourceManager.GetString("CHEMBL12760_doublebondadjacenttoupbond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///          11280714582D 1   1.00000     0.00000     0
        ///
        /// 28 29  0     1  0            999 V2000
        ///    2.8917   -3.2792    0.0000 N   0  0  3  0  0  0           0  0  0
        ///    3.7792   -3.5792    0.0000 C   0  0  0  0  0  0           0  0  0
        ///    4.3292   -2.8042    0.0000 C   0  0  0  0  0  0           0  0  0
        ///    1.9167   -3.2792    0.0000 C   0  0  0  0  0  0           0  0  0
        ///    4.5417   -1.5292    0.0000 C   0  0  2  0  0  0           0  0  0
        ///    2.8917   -2.3542    0.0000 C   0  0  3  0  0  0        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CHEMBL50821_stereobondadjacenttodoublebond {
            get {
                return ResourceManager.GetString("CHEMBL50821_stereobondadjacenttodoublebond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  SciTegic05161214222D
        ///
        /// 20 21  0  0  1  0            999 V2000
        ///    8.2095   -0.8695    0.0000 S   0  0
        ///    7.5078   -0.4389    0.0000 C   0  0
        ///    7.5236    0.3847    0.0000 C   0  0
        ///    6.8190    0.8152    0.0000 C   0  0
        ///    6.0993    0.4184    0.0000 C   0  0
        ///    6.0778   -0.4101    0.0000 C   0  0
        ///    6.7818   -0.8387    0.0000 C   0  0
        ///    5.3924    0.8515    0.0000 F   0  0
        ///    7.8020   -1.5888    0.0000 O   0  0
        ///    8.6287   -1.5784    0.0000 O   0  0
        ///    8.9235   -0.4521    0.0000 N  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string chiralflagset {
            get {
                return ResourceManager.GetString("chiralflagset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0
        ///CBDIGESTER0125130522
        ///
        /// 72 78  0  0001  0  0  0  0  0999 V2000
        ///  174.3984 -117.2500    0.0000 C   0  0  0  0  0  0  0  0  0  0  0
        ///  174.3984 -142.7500    0.0000 C   0  0  0  0  0  0  0  0  0  0  0
        ///  196.5000 -155.5000    0.0000 O   0  0  0  0  0  0  0  0  0  0  0
        ///  218.6016 -142.7500    0.0000 C   0  0  0  0  0  0  0  0  0  0  0
        ///  218.6016 -117.2500    0.0000 C   0  0  0  0  0  0  0  0  0  0  0
        ///  196.5000 -104.5000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0
        ///  152.3008 -104.5000    0.0000 O   0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string degeneratestereocenters {
            get {
                return ResourceManager.GetString("degeneratestereocenters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  ACD/Labs03151017442D
        ///
        /// 14 14  0  0000  0  0  0  0  0999 V2000
        ///    6.9019   -2.6546    0.0000 C   0  0  0  0  0  0  0  0  0  0  0
        ///    5.7516   -1.9950    0.0000 C   0  0  0  0  0  0  0  0  0  0  0
        ///    4.6013   -2.6707    0.0000 N   0  0  0  0  0  0  0  0  0  0  0
        ///    5.7436   -0.6596    0.0000 O   0  0  0  0  0  0  0  0  0  0  0
        ///    8.0442   -1.9950    0.0000 D   0  0  0  0  0  0  0  0  0  0  0
        ///    6.8939   -3.9819    0.0000 D   0  0  0  0  0  0  0  0  0  0  0
        ///    8.0442   -3.3223    0.0000 D    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string deuteratedmolecule {
            get {
                return ResourceManager.GetString("deuteratedmolecule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///MOLFACTORY0125130518
        ///
        /// 19 18  0  0000  0  0  0  0  0999 V2000
        ///   92.6250 -153.9134    0.0000 C   0  0  0  0  0  0  0  0  0  0  0
        ///   79.8750 -175.9970    0.0000 C   0  0  0  0  0  0  0  0  0  0  0
        ///   92.6250 -198.0807    0.0000 C   0  0  0  0  0  0  0  0  0  0  0
        ///  118.1250 -198.0807    0.0000 C   0  0  0  0  0  0  0  0  0  0  0
        ///  130.8750 -175.9970    0.0000 N   0  0  0  0  0  0  0  0  0  0  0
        ///  118.1250 -153.9134    0.0000 C   0  0  0  0  0  0  0  0  0  0  0
        ///  156.3750 -175.9970    0.0000 I   0  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dodgyiodine {
            get {
                return ResourceManager.GetString("dodgyiodine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  -ISIS-  03141118062D
        ///
        /// 13 14  0  0  0  0  0  0  0  0999 V2000
        ///   -1.1014   -1.3791    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -1.1026   -2.2065    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -0.3878   -2.6194    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -0.3896   -0.9664    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    0.3258   -1.3755    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    0.3261   -2.2065    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    1.1165   -2.4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string doublebond {
            get {
                return ResourceManager.GetString("doublebond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  SciTegic03291108552D
        ///
        /// 30 32  0  0  1  0            999 V2000
        ///    2.2353   -4.3369    0.0000 Cl  0  0
        ///    4.7350    0.0000    0.0000 Cl  0  0
        ///   -1.3318    0.5780    0.0000 O   0  0
        ///   -1.8417    2.1473    0.0000 O   0  0
        ///    0.2821   -1.0999    0.0000 N   0  0
        ///    0.2821    0.2350    0.0000 N   0  0
        ///   -1.0278   -0.4325    0.0000 N   0  0
        ///    1.0667   -0.8450    0.0000 C   0  0
        ///    1.0667   -0.0200    0.0000 C   0  0
        ///   -0.2028   -0.4325    0.0000 C   0  0  3  0  0  0
        ///    0.0272   -1.8845  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string doublebondwithattachedeitherbond {
            get {
                return ResourceManager.GetString("doublebondwithattachedeitherbond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///csCF1100/07161309022D
        ///
        /// 18 19  0  0  0  0  0  0  0  0999 V2000
        ///   30.4902  -42.8251    0.0000 C   0  0  1  0  0  0  0  0  0  0  0  0
        ///   31.9062  -42.8251    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
        ///   32.9058  -41.8672    0.0000 C   0  0  2  0  0  0  0  0  0  0  0  0
        ///   32.9058  -40.4512    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   31.9062  -39.4517    0.0000 C   0  0  2  0  0  0  0  0  0  0  0  0
        ///   30.4902  -39.4517    0.0000 C   0  0  3  0  0  0  0  0  0  0  0  0
        ///   29.5323  -40.45 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string doublebondwithattachedwavybond {
            get {
                return ResourceManager.GetString("doublebondwithattachedwavybond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  ACD/Labs09241317182D
        ///
        /// 48 48  0  0000  0  0  0  0  0999 V2000
        ///   13.0356   -0.5171    0.0000 O   0  0  0  0  0  0  0  0  0  0  0
        ///    3.7270   -6.2057    0.0000 O   0  0  0  0  0  0  0  0  0  0  0
        ///   12.3223  -10.2537    0.0000 O   0  0  0  0  0  0  0  0  0  0  0
        ///   11.6090   -2.9780    0.0000 C   0  0  0  0  0  0  0  0  0  0  0
        ///    2.3004  -10.3072    0.0000 C   0  0  0  0  0  0  0  0  0  0  0
        ///   12.3223  -15.1755    0.0000 C   0  0  0  0  0  0  0  0  0  0  0
        ///   13.0356   -2.1577    0.0000 C    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string duplicatemolecules_counterexample {
            get {
                return ResourceManager.GetString("duplicatemolecules_counterexample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  Ketcher 09251308582D 1   1.00000     0.00000     0
        ///
        /// 44 44  0     0  0            999 V2000
        ///    9.8012   -0.3888    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
        ///    2.8022   -4.6659    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
        ///    9.2648   -7.7095    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
        ///    8.7285   -2.2391    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    1.7296   -7.7497    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    9.2648  -11.4101    0.0000 C   0  0  0  0  0  0  0  0  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string duplicatemolecules_example {
            get {
                return ResourceManager.GetString("duplicatemolecules_example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  SMMXDraw02141308032D
        ///
        /// 16 17  0  0  0  0  0  0  0  0999 V2000
        ///    9.2278   -5.6901    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   11.2701   -5.6896    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   10.2509   -5.0998    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
        ///   11.2701   -6.8710    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    9.2278   -6.8763    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   10.2534   -7.4606    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    8.2033   -7.4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string eitherbond_molecule {
            get {
                return ResourceManager.GetString("eitherbond_molecule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WPM00631
        /// addWPLinks.groovy
        ///
        ///  1  0  0  0  0  0            999 V2000
        ///    0.0000    0.0000    0.0000 e   0  5  0  0  0  0  0  0  0  0  0  0
        ///M  CHG  1   1  -1
        ///M  RAD  1   1   2
        ///M  END
        ///&gt; &lt;WPM&gt;
        ///WPM00631
        ///
        ///&gt; &lt;http://www.wikipathways.org/index.php/Pathway:WP2670&gt;
        ///Iron uptake and transport (Homo sapiens)
        ///
        ///&gt; &lt;Label0&gt;
        ///e-
        ///
        ///&gt; &lt;http://semanticscience.org/resource/CHEMINF_000407&gt;
        ///CHEBI:10545
        ///
        ///$$$$
        ///.
        /// </summary>
        internal static string electron {
            get {
                return ResourceManager.GetString("electron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled Document-1
        ///  ChemDraw07021510572D
        ///
        ///  0  0  0  0  0  0  0  0  0  0999 V2000
        ///M  END.
        /// </summary>
        internal static string empty {
            get {
                return ResourceManager.GetString("empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  Mrv0541 02231217132D          
        ///
        /// 22 23  0  0  1  0            999 V2000
        ///    0.1067    5.5902    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
        ///    0.1067    4.7652    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -0.6078    4.3527    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -0.6078    3.5277    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -1.3222    3.1152    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -1.3222    2.2902    0.0000 C   0  0  1  0  0  0  0  0  0  0  0  0
        ///   -0.6 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string enol {
            get {
                return ResourceManager.GetString("enol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 81058728
        ///  -OEChem-07021012202D
        ///
        ///865988  0     0  0  0  0  0  0999 V2000
        ///   32.5541  -54.6870    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
        ///   38.7355  -60.9134    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
        ///   32.5541  -67.0798    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
        ///   26.3126  -60.9134    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
        ///   27.2807  -48.3120    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
        ///   37.8275  -48.3120    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
        ///   45.110 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string enormousmolecule {
            get {
                return ResourceManager.GetString("enormousmolecule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  DemoDemo00000000000D
        ///
        ///  0  0  0     0  0            999 V3000
        ///M  V30 BEGIN CTAB
        ///M  V30 COUNTS 13 12 0 0 0
        ///M  V30 BEGIN ATOM
        ///M  V30 1 C 21.3125 -8.5583 0 0 CHG=-1 CFG=3 
        ///M  V30 2 C 20.3575 -9.2521 0 0 
        ///M  V30 3 C 20.7222 -10.375 0 0 
        ///M  V30 4 C 21.9028 -10.375 0 0 
        ///M  V30 5 C 22.2675 -9.2521 0 0 
        ///M  V30 6 C 22.2363 -4.6896 0 0 
        ///M  V30 7 C 21.8715 -5.8125 0 0 
        ///M  V30 8 C 20.691 -5.8125 0 0 
        ///M  V30 9 C 20.3262 -4.6896 0 0 
        ///M  V30 10 C 21.2813 -3.9958 0 0 CHG=-1 CFG=3 
        ///M  V30 11 * 21.2188 -4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ferrocene_v3000 {
            get {
                return ResourceManager.GetString("ferrocene_v3000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  ACD/Labs04190708532D
        ///
        /// 19 21  0  0  0  0  0  0  0  0  1 V2000
        ///    5.9836   -6.9094    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    6.6469   -5.7555    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    5.9836   -4.6086    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    4.6569   -4.6086    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    3.9867   -5.7555    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    4.6569   -6.9094    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    3.9867   -3.4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string fixedvalence {
            get {
                return ResourceManager.GetString("fixedvalence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  Ketcher 11141411112D 1   1.00000     0.00000     0
        ///
        /// 15 15  0     0  0            999 V2000
        ///    5.4213    4.8582    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    6.2873    4.3582    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    7.1533    4.8582    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    8.0194    4.3582    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    8.8854    4.8582    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    9.7514    4.3582    0.0000 C   0  0  0  0  0  0  0  0  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string fourstereobondsatcentre {
            get {
                return ResourceManager.GetString("fourstereobondsatcentre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  Ketcher 11171412172D 1   1.00000     0.00000     0
        ///
        /// 15 15  0     0  0            999 V2000
        ///    5.4214    4.8583    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    6.2874    4.3582    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    7.1534    4.8583    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    8.0195    4.3582    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    8.8855    4.8583    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    9.7515    4.3582    0.0000 C   0  0  0  0  0  0  0  0  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string fourstereobondsatcentre_counterexample {
            get {
                return ResourceManager.GetString("fourstereobondsatcentre_counterexample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  -INDIGO-03081306442D
        ///
        /// 11 12  0  0  0  0  0  0  0  0999 V2000
        ///    3.2789    2.0625    0.0000 Cl  0  0  0  0  0  0  0  0  0  0  0  0
        ///    3.2789    1.2375    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    3.9934    0.8250    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
        ///    3.9934    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    4.7079   -0.4125    0.0000 Br  0  0  0  0  0  0  0  0  0  0  0  0
        ///    3.2789   -0.4125    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
        ///    2.5645    0.0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string fusedrings {
            get {
                return ResourceManager.GetString("fusedrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///csCF1100/07161309022D
        ///
        /// 61 63  0  0  0  0  0  0  0  0999 V2000
        ///    4.4221-1060.8869    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    4.4221-1062.3869    0.0000 C   0  0  1  0  0  0  0  0  0  0  0  0
        ///    5.7179-1063.1369    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    7.0095-1062.3869    0.0000 C   0  0  1  0  0  0  0  0  0  0  0  0
        ///    7.0095-1060.8869    0.0000 C   0  0  1  0  0  0  0  0  0  0  0  0
        ///    5.7179-1060.1452    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    3.1221-1063.13 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string goodallene {
            get {
                return ResourceManager.GetString("goodallene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0
        ///CBDIGESTER0125130521
        ///
        /// 50 51  0  0001  0  0  0  0  0999 V2000
        ///  264.0000  -64.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0
        ///  289.5000  -64.0000    0.0000 N   0  0  0  0  0  0  0  0  0  0  0
        ///  264.0000  -89.5000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0
        ///  264.0000 -115.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0
        ///  264.0000 -140.5000    0.0000 N   0  0  0  0  0  0  0  0  0  0  0
        ///  289.5000 -140.5000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0
        ///  315.0000 -140.5000    0.0000 C   0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string implicithydrogen {
            get {
                return ResourceManager.GetString("implicithydrogen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  Ketcher 02271312552D 1   1.00000     0.00000     0
        ///
        /// 54 31  0     0  0            999 V2000
        ///    2.9191   -4.2784    0.0000 S   0  0  0  0  0  0  0  0  0  0  0  0
        ///    3.1370   -3.4648    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
        ///    3.1370   -5.0919    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
        ///    2.1897   -3.8572    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
        ///    2.1169   -4.9692    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
        ///    3.2273   -2.1966    0.0000 O   0  0  0  0  0  0  0  0  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string inorganicresidues {
            get {
                return ResourceManager.GetString("inorganicresidues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  SMMXDraw02141318452D
        ///
        /// 58 35  0  0  0  0  0  0  0  0999 V2000
        ///    4.0938   -6.0000    0.0000 S   0  0  3  0  0  0  0  0  0  0  0  0
        ///    4.3994   -4.8591    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
        ///    4.3994   -7.1409    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
        ///    3.0709   -5.4094    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
        ///    2.9688   -6.9688    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
        ///    4.5260   -3.0806    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
        ///    4.6282   -1.5 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string inorganicresidues2 {
            get {
                return ResourceManager.GetString("inorganicresidues2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  -INDIGO-03271307422D
        ///
        /// 12 12  0  0  0  0  0  0  0  0999 V2000
        ///    4.2868    0.0000    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
        ///    3.5724   -0.4125    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    3.5724   -1.2375    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
        ///    2.8579    0.0000    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
        ///    2.1434   -0.4125    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    1.4289    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    0.7145   -0.4125    0.0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string iodine123 {
            get {
                return ResourceManager.GetString("iodine123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  -INDIGO-03051314002D
        ///
        /// 43 50  0  0  1  0  0  0  0  0999 V2000
        ///    1.1989   -1.1741    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    1.7263   -0.5397    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    1.5231    0.2599    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    0.5856    0.7804    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    0.1729    1.4948    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    0.7003    2.1292    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
        ///    0.2599    2.8 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ironporphyrin {
            get {
                return ResourceManager.GetString("ironporphyrin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 646: fails in OE
        ///  Mrv0541 02231214512D          
        ///
        /// 65 66  0  0001  0  0  0  0  0999 V2000
        ///    4.9509    3.3001    0.0000 O   0  0  0  0  0  0  0  0  0  0  0
        ///    4.2365    2.0625    0.0000 O   0  0  0  0  0  0  0  0  0  0  0
        ///    2.8075    2.8876    0.0000 O   0  0  0  0  0  0  0  0  0  0  0
        ///    4.2365    5.3626    0.0000 O   0  0  0  0  0  0  0  0  0  0  0
        ///    7.0944    2.0625    0.0000 O   0  0  0  0  0  0  0  0  0  0  0
        ///    5.3832    1.1878    0.0000 O   0  0  0  0  0  0  0  0  0  0  0
        ///    9.237 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string layoutfail {
            get {
                return ResourceManager.GetString("layoutfail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  ACD/Labs09241317182D
        ///
        /// 48 48  0  0000  0  0  0  0  0999 V2000
        ///   13.0356   -0.5171    0.0000 O   0  0  0  0  0  0  0  0  0  0  0
        ///    3.7270   -6.2057    0.0000 O   0  0  0  0  0  0  0  0  0  0  0
        ///   12.3223  -10.2537    0.0000 O   0  0  0  0  0  0  0  0  0  0  0
        ///   11.6090   -2.9780    0.0000 C   0  0  0  0  0  0  0  0  0  0  0
        ///    2.3004  -10.3072    0.0000 C   0  0  0  0  0  0  0  0  0  0  0
        ///   12.3223  -15.1755    0.0000 C   0  0  0  0  0  0  0  0  0  0  0
        ///   13.0356   -2.1577    0.0000 C    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string moleculeWithInChIProps {
            get {
                return ResourceManager.GetString("moleculeWithInChIProps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  Mrv0541 04191212142D          
        ///
        ///124138  0  0000  0  0  0  0  0999 V2000
        ///    4.1932   -6.8435    0.0000 C   0  0  0  0  0  0  0  0  0  0  0
        ///    4.6775   -7.5113    0.0000 N   0  0  0  0  0  0  0  0  0  0  0
        ///    3.4083   -7.0977    0.0000 C   0  0  0  0  0  0  0  0  0  0  0
        ///    4.1920   -8.1783    0.0000 C   0  0  0  0  0  0  0  0  0  0  0
        ///    3.4076   -7.9228    0.0000 C   0  0  0  0  0  0  0  0  0  0  0
        ///    4.4488   -6.0590    0.0000 C   0  0  0  0  0  0  0  0  0  0  0
        ///    4.4463   -8.9631    0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mystery {
            get {
                return ResourceManager.GetString("mystery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  SciTegic02131210132D
        ///
        /// 26 31  0  0  1  0            999 V2000
        ///    5.2036   -1.6911    0.0000 O   0  0
        ///    4.7785    0.2393    0.0000 O   0  0
        ///    3.3767   -2.5764    0.0000 O   0  0
        ///    7.0343   -1.3089    0.0000 O   0  0
        ///    2.9409    0.4818    0.0000 N   0  0
        ///    4.3536   -0.6747    0.0000 C   0  0  1  0  0  0
        ///    4.0206   -0.0865    0.0000 C   0  0  2  0  0  0
        ///    5.1177   -0.3481    0.0000 C   0  0
        ///    4.3715   -1.5195    0.0000 C   0  0
        ///    3.7874    0.6760    0.0000 C   0  0
        ///    5.652 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string nonoppositebondsmatch {
            get {
                return ResourceManager.GetString("nonoppositebondsmatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  -INDIGO-02211315332D
        ///
        /// 33 35  0  0  1  0  0  0  0  0999 V2000
        ///   17.6166  -11.4319    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
        ///   10.8803   -5.9882    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
        ///   16.2626   -5.9858    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
        ///   17.6166   -6.7706    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
        ///   18.9509  -12.2155    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
        ///   21.6461  -10.6790    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
        ///   23.2210   -5.4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string nonstereohydrogens2 {
            get {
                return ResourceManager.GetString("nonstereohydrogens2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  -INDIGO-03251322022D
        ///
        /// 16 15  0  0  1  0  0  0  0  0999 V2000
        ///   12.1995   -5.4501    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   11.4851   -5.8626    0.0000 C   0  0  1  0  0  0  0  0  0  0  0  0
        ///   10.7706   -5.4501    0.0000 C   0  0  2  0  0  0  0  0  0  0  0  0
        ///   10.0561   -5.8626    0.0000 C   0  0  1  0  0  0  0  0  0  0  0  0
        ///    9.3417   -5.4501    0.0000 C   0  0  2  0  0  0  0  0  0  0  0  0
        ///   12.1995   -4.6251    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
        ///   10.7706   -4.6 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string nonstereohydrogens3 {
            get {
                return ResourceManager.GetString("nonstereohydrogens3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  SMMXDraw03281309562D
        ///
        /// 22 22  0  0  1  0  0  0  0  0999 V2000
        ///   13.8150  -10.4071    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   12.4656   -9.0446    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    9.9623   -9.7492    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   11.2829   -9.0446    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    9.7974   -7.5557    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
        ///   10.9209   -7.9203    0.0000 C   0  0  3  0  0  0  0  0  0  0  0  0
        ///   11.8743   -7.2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string nonstereohydrogens4 {
            get {
                return ResourceManager.GetString("nonstereohydrogens4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  Mrv0541 02231214272D          
        ///
        /// 13 13  0  0001  0  0  0  0  0999 V2000
        ///    0.0000    0.0000    0.0000 O   0  0  0  0  0  0  0  0  0  0  0
        ///   -0.8974   -1.9370    0.0000 O   0  0  0  0  0  0  0  0  0  0  0
        ///    0.8974   -1.9370    0.0000 O   0  0  0  0  0  0  0  0  0  0  0
        ///    0.6674   -0.4849    0.0000 C   0  0  0  0  0  0  0  0  0  0  0
        ///    1.4521   -0.2300    0.0000 O   0  0  0  0  0  0  0  0  0  0  0
        ///    0.4125   -1.2695    0.0000 C   0  0  0  0  0  0  0  0  0  0  0
        ///   -0.4125   -1.2695    0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string nonstereohydrogens5 {
            get {
                return ResourceManager.GetString("nonstereohydrogens5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  Mrv0541 02231215382D          
        ///
        /// 26 28  0  0  1  0            999 V2000
        ///   -3.4255   -1.9958    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -2.6719   -2.3314    0.0000 C   0  0  1  0  0  0  0  0  0  0  0  0
        ///   -2.5856   -3.1518    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -2.0044   -1.8464    0.0000 C   0  0  1  0  0  0  0  0  0  0  0  0
        ///   -2.0907   -1.0260    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -1.2508   -2.1820    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -0.5 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string noproblemsmolecule {
            get {
                return ResourceManager.GetString("noproblemsmolecule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  SciTegic08161218152D
        ///
        ///153169  0  0  1  0            999 V2000
        ///    5.4402   -6.4194    0.0000 C   0  0  2  0  0  0
        ///   13.8471   -6.4194    0.0000 C   0  0  2  0  0  0
        ///   10.0970   -1.2694    0.0000 C   0  0  1  0  0  0
        ///    7.2463   -0.3120    0.0000 C   0  0  1  0  0  0
        ///    6.1583   -6.8546    0.0000 N   0  0
        ///   14.5579   -6.0712    0.0000 N   0  0
        ///    8.3996   -1.5450    0.0000 C   0  0  1  0  0  0
        ///    9.0525   -2.4590    0.0000 C   0  0  2  0  0  0
        ///    4.7438   -7.6018    0.0000 N   0  0
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string onebonduponebonddown {
            get {
                return ResourceManager.GetString("onebonduponebonddown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  SciTegic11061219412D
        ///
        /// 36 40  0  0  0  0            999 V2000
        ///   -5.4006   -6.0313    0.0000 C   0  0  2  0  0  0
        ///   -6.1151   -5.6188    0.0000 O   0  0
        ///   -6.8295   -6.0313    0.0000 C   0  0  1  0  0  0
        ///   -6.8296   -6.8563    0.0000 C   0  0  1  0  0  0
        ///   -6.1151   -7.2688    0.0000 C   0  0  1  0  0  0
        ///   -5.4006   -6.8563    0.0000 C   0  0  1  0  0  0
        ///   -3.6493   -4.3726    0.0000 O   0  0
        ///   -4.6861   -7.2688    0.0000 O   0  0
        ///   -6.1151   -8.0938    0.0000 O   0  0
        ///   -7.5440   - [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string oppositebondmismatch {
            get {
                return ResourceManager.GetString("oppositebondmismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0
        ///CBDIGESTER0125130520
        ///
        /// 20 22  0  0001  0  0  0  0  0999 V2000
        ///  108.8984 -182.2500    0.0000 C   0  0  0  0  0  0  0  0  0  0  0
        ///  108.8984 -207.7500    0.0000 C   0  0  0  0  0  0  0  0  0  0  0
        ///  131.0000 -220.5000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0
        ///  153.1016 -207.7500    0.0000 C   0  0  0  0  0  0  0  0  0  0  0
        ///  153.1016 -182.2500    0.0000 C   0  0  0  0  0  0  0  0  0  0  0
        ///  131.0000 -169.5000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0
        ///  175.1992 -220.5000    0.0000 C   0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string oppositebondsmismatch {
            get {
                return ResourceManager.GetString("oppositebondsmismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  -INDIGO-07091511462D
        ///
        /// 11 11  0  0000  0  0  0  0  0999 V2000
        ///    1.3856   -2.4000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0
        ///   -2.7713    1.6000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0
        ///   -1.3856    2.4000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0
        ///   -1.3856   -0.8000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0
        ///   -4.1569   -0.8000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0
        ///   -2.7713    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0
        ///    0.0000    1.6000    0.0000 C    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string partiallyionizedvanillamide {
            get {
                return ResourceManager.GetString("partiallyionizedvanillamide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0
        ///CBDIGESTER1216131122
        ///
        /// 12 12  0  0000  0  0  0  0  0999 V2000
        ///  128.4163 -161.0101    0.0000 C   0  0  0  0  0  0  0  0  0  0  0
        ///  113.4163 -186.9908    0.0000 C   0  0  0  0  0  0  0  0  0  0  0
        ///  142.2620 -178.7467    0.0000 C   0  0  0  0  0  0  0  0  0  0  0
        ///  171.2820 -186.9908    0.0000 C   0  0  0  0  0  0  0  0  0  0  0
        ///  186.2856 -161.0101    0.0000 O   0  0  0  0  0  0  0  0  0  0  0
        ///  157.4377 -169.2514    0.0000 C   0  0  0  0  0  0  0  0  0  0  0
        ///  149.6732 -140.2736    0.0000 C   0  0  0  0  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string perspectivesugar {
            get {
                return ResourceManager.GetString("perspectivesugar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled Document-1
        ///  ChemDraw07151511582D
        ///
        ///  7  7  0  0  0  0  0  0  0  0999 V2000
        ///   -0.7145    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -0.7145   -0.8250    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    0.0000   -1.2375    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    0.7145   -0.8250    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    0.7145    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    0.0000    0.4125    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string radical_one {
            get {
                return ResourceManager.GetString("radical_one", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to radical_two.mol
        ///  ChemDraw07151511592D
        ///
        ///  9  9  0  0  0  0  0  0  0  0999 V2000
        ///   -0.7145    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -0.7145   -0.8250    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    0.0000   -1.2375    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    0.7145   -0.8250    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    0.7145    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    0.0000    0.4125    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string radical_three {
            get {
                return ResourceManager.GetString("radical_three", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to radical_one.mol
        ///  ChemDraw07151511592D
        ///
        ///  8  8  0  0  0  0  0  0  0  0999 V2000
        ///   -1.0717    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -1.0717   -0.8250    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -0.3572   -1.2375    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    0.3572   -0.8250    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    0.3572    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -0.3572    0.4125    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string radical_two {
            get {
                return ResourceManager.GetString("radical_two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  SciTegic05161214222D
        ///
        /// 20 21  0  0  0  0            999 V2000
        ///    8.2095   -0.8695    0.0000 S   0  0
        ///    7.5078   -0.4389    0.0000 C   0  0
        ///    7.5236    0.3847    0.0000 C   0  0
        ///    6.8190    0.8152    0.0000 C   0  0
        ///    6.0993    0.4184    0.0000 C   0  0
        ///    6.0778   -0.4101    0.0000 C   0  0
        ///    6.7818   -0.8387    0.0000 C   0  0
        ///    5.3924    0.8515    0.0000 F   0  0
        ///    7.8020   -1.5888    0.0000 O   0  0
        ///    8.6287   -1.5784    0.0000 O   0  0
        ///    8.9235   -0.4521    0.0000 N  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string relativestereo {
            get {
                return ResourceManager.GetString("relativestereo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///          11290715122D 1   1.00000     0.00000     0
        ///
        /// 56 59  0     0  0            999 V2000
        ///   -0.8074  -11.0482    0.0000 C   0  0  0  0  0  0           0  0  0
        ///   -0.8074  -11.8704    0.0000 O   0  0  0  0  0  0           0  0  0
        ///   -0.0974  -12.2783    0.0000 C   0  0  1  0  0  0           0  0  0
        ///    0.6188  -11.8704    0.0000 O   0  0  0  0  0  0           0  0  0
        ///    0.6188  -11.0482    0.0000 C   0  0  2  0  0  0           0  0  0
        ///   -0.0974  -10.6274    0.0000 C   0  0  0  0  0  0        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string rifampin {
            get {
                return ResourceManager.GetString("rifampin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  Ketcher 11141408252D 1   1.00000     0.00000     0
        ///
        /// 12 13  0     0  0            999 V2000
        ///    8.9920   -2.7958    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    9.8645   -3.2996    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    9.8645   -4.3071    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    8.9920   -4.8108    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    8.1195   -4.3071    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    8.1195   -3.2996    0.0000 C   0  0  0  0  0  0  0  0  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ringstereo_absent {
            get {
                return ResourceManager.GetString("ringstereo_absent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  Ketcher 11131407192D 1   1.00000     0.00000     0
        ///
        /// 12 13  0     0  0            999 V2000
        ///    8.9250   -2.7750    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    9.7910   -3.2750    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    9.7910   -4.2750    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    8.9250   -4.7750    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    8.0590   -4.2750    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    8.0590   -3.2750    0.0000 C   0  0  0  0  0  0  0  0  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ringstereo_present {
            get {
                return ResourceManager.GetString("ringstereo_present", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.i 2 salt
        ///  -INDIGO-03311320142D
        ///
        ///  5  3  0  0  0  0  0  0  0  0999 V2000
        ///   10.2578  -10.1002    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   11.2806   -9.5096    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   12.5703  -10.1627    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
        ///   11.2806   -6.6410    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
        ///   16.6563   -4.6563    0.0000 Na  0  0  0  0  0 15  0  0  0  0  0  0
        ///  1  2  1  0  0  0  0
        ///  2  3  1  0  0  0  0
        ///  2  4  2  0  0  0  0
        ///M  END.
        /// </summary>
        internal static string sodiumcarboxylicacid {
            get {
                return ResourceManager.GetString("sodiumcarboxylicacid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  ChemDraw10011414542D
        ///
        /// 32 32  0  0  0  0  0  0  0  0999 V2000
        ///   -2.8742    0.1115    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -2.1597    0.5240    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -1.4453    0.1115    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -0.7308    0.5240    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -0.0163    0.1115    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -2.8742   -0.7135    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -3.5887   -1.1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string stereobondatdoublebond {
            get {
                return ResourceManager.GetString("stereobondatdoublebond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  ChemDraw07281414292D
        ///
        /// 24 24  0  0  0  0  0  0  0  0999 V2000
        ///   -3.9856    0.1070    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -3.2712    0.5195    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -2.5567    0.1070    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -1.8422    0.5195    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -1.1277    0.1070    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -0.4133    0.5195    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    0.3012    0.1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string stereobondatdoublebond_allene {
            get {
                return ResourceManager.GetString("stereobondatdoublebond_allene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///csCF1100/07161309022D
        ///
        /// 71 77  0  0  0  0  0  0  0  0999 V2000
        ///   22.4441 -328.5285    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   24.2941 -322.7202    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   24.2941 -324.2202    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   25.5899 -324.9702    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   26.8816 -324.2202    0.0000 C   0  0  1  0  0  0  0  0  0  0  0  0
        ///   26.8816 -322.7202    0.0000 C   0  0  2  0  0  0  0  0  0  0  0  0
        ///   25.5899 -321.97 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string stereobondatdoublebond_false {
            get {
                return ResourceManager.GetString("stereobondatdoublebond_false", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 157
        ///  Mrv0541 02231214292D          
        ///
        /// 44 48  0  0  1  0            999 V2000
        ///    6.9922    1.8744    0.0000 P   0  0  1  0  0  0  0  0  0  0  0  0
        ///    8.4135    2.0213    0.0000 P   0  0  2  0  0  0  0  0  0  0  0  0
        ///    4.9010    0.4187    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
        ///   11.3032    2.2426    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
        ///    3.8647    2.2851    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
        ///    2.8071    0.8348    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
        ///   1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string stereobondatdoublebond_phosphate {
            get {
                return ResourceManager.GetString("stereobondatdoublebond_phosphate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  Ketcher 11141414272D 1   1.00000     0.00000     0
        ///
        ///  7  6  0     1  0            999 V2000
        ///    8.7797   -6.8879    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
        ///   10.3384   -6.8879    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    9.5546   -5.5263    0.0000 Cl  0  0  0  0  0  0  0  0  0  0  0  0
        ///   10.3384   -5.9802    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   10.9849   -7.5343    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
        ///   11.1315   -5.5263    0.0000 F   0  0  0  0  0  0  0  0  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string stereobondbetweenstereocentres_false {
            get {
                return ResourceManager.GetString("stereobondbetweenstereocentres_false", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  Ketcher 11141413332D 1   1.00000     0.00000     0
        ///
        ///  9  8  0     1  0            999 V2000
        ///    8.4902   -5.8647    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    9.3172   -6.3464    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    9.3172   -7.3096    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
        ///   10.9714   -7.3096    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   10.1395   -5.8647    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   10.9714   -6.3464    0.0000 C   0  0  0  0  0  0  0  0  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string stereobondbetweenstereocentres_true {
            get {
                return ResourceManager.GetString("stereobondbetweenstereocentres_true", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  -INDIGO-03201314512D
        ///
        ///  9  8  0  0  1  0  0  0  0  0999 V2000
        ///    5.0938   -5.8125    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    7.0313   -4.4375    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    8.8438   -5.8125    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   11.5000   -4.2813    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   13.4063   -5.5313    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   15.8750   -3.9375    0.0000 C   0  0  2  0  0  0  0  0  0  0  0  0
        ///   18.1250   -5.4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string stereoinversion {
            get {
                return ResourceManager.GetString("stereoinversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  ACD/Labs08051415442D
        ///
        /// 39 40  0  0  0  0  0  0  0  0  4 V2000
        ///   36.5923   -7.2868    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   38.3636   -5.5155    0.0000 O   0  5  0  0  0  0  0  0  0  0  0  0
        ///   38.3636   -9.0581    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   34.1082   -7.2868    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
        ///   36.5923  -10.8078    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   40.8477   -9.0581    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
        ///   38.3420  -12.5 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string substitutedatommolecule {
            get {
                return ResourceManager.GetString("substitutedatommolecule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  ACD/Labs07221416132D
        ///
        /// 32 34  0  0  1  0  0  0  0  0  3 V2000
        ///    4.6195   -5.4903    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    4.2266   -6.7010    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    5.2567   -7.4550    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    6.2868   -6.7010    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    5.8939   -5.4903    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    7.5081   -7.0939    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    7.7736   -8.3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tenradicalcentres {
            get {
                return ResourceManager.GetString("tenradicalcentres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  SciTegic05301215452D
        ///
        /// 43 50  0  0  1  0            999 V2000
        ///    4.0568   -7.5086    0.0000 O   0  0
        ///    3.7375   -7.8968    0.0000 O   0  0
        ///    1.7702   -7.5594    0.0000 O   0  0
        ///   -4.9262   -5.0954    0.0000 O   0  0
        ///   -4.6070   -4.7072    0.0000 O   0  0
        ///   -2.6397   -5.0446    0.0000 O   0  0
        ///    0.4440   -6.9493    0.0000 O   0  0
        ///   -1.3134   -5.6547    0.0000 O   0  0
        ///    3.1463   -6.7723    0.0000 C   0  0  2  0  0  0
        ///    2.7938   -7.4975    0.0000 C   0  0  1  0  0  0
        ///    3.415 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string toosmallangle {
            get {
                return ResourceManager.GetString("toosmallangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///          11280715092D 1   1.00000     0.00000     0
        ///
        /// 44 49  0     1  0            999 V2000
        ///    1.9042   -4.2500    0.0000 C   0  0  0  0  0  0           0  0  0
        ///    1.3000   -5.3167    0.0000 C   0  0  2  0  0  0           0  0  0
        ///    1.8083   -5.8125    0.0000 C   0  0  0  0  0  0           0  0  0
        ///    0.7083   -6.3958    0.0000 C   0  0  0  0  0  0           0  0  0
        ///   -0.5125   -6.4500    0.0000 C   0  0  3  0  0  0           0  0  0
        ///   -1.1500   -6.1792    0.0000 C   0  0  3  0  0  0        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tritiatedmolecule {
            get {
                return ResourceManager.GetString("tritiatedmolecule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  Ketcher 11141411462D 1   1.00000     0.00000     0
        ///
        /// 10  9  0     0  0            999 V2000
        ///    4.3500   -3.6500    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    5.2160   -4.1500    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    6.0821   -3.6500    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    6.9481   -4.1500    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    7.8141   -3.6500    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    8.6801   -4.1500    0.0000 C   0  0  0  0  0  0  0  0  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tshapedmolecule {
            get {
                return ResourceManager.GetString("tshapedmolecule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  Ketcher 11141412032D 1   1.00000     0.00000     0
        ///
        /// 10  9  0     0  0            999 V2000
        ///    4.3500   -3.6500    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    5.2160   -4.1500    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    6.0821   -3.6500    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    6.9481   -4.1500    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    7.8141   -3.6500    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    8.6801   -4.1500    0.0000 C   0  0  0  0  0  0  0  0  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tshapedmolecule_2 {
            get {
                return ResourceManager.GetString("tshapedmolecule_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  ChemDraw09081414522D
        ///
        /// 35 38  0  0  0  0  0  0  0  0999 V2000
        ///   -3.8771   -0.8549    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -3.8771   -1.6799    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -3.1627   -2.0924    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -2.4482   -1.6799    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -2.4482   -0.8549    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -3.1627   -0.4424    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -1.7337   -2.0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string twostereobondsoneinwardoneoutward {
            get {
                return ResourceManager.GetString("twostereobondsoneinwardoneoutward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  Ketcher 01231413142D 1   1.00000     0.00000     0
        ///
        ///  2  0  0     0  0            999 V2000
        ///   -3.4000    2.1500    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
        ///    0.5500    1.9750    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
        ///M  END
        ///
        ///$$$$.
        /// </summary>
        internal static string twowaters {
            get {
                return ResourceManager.GetString("twowaters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0
        ///CBDIGESTER0125130523
        ///
        /// 34 36  0  0001  0  0  0  0  0999 V2000
        ///    2.4621    0.8000    0.0000 O   0  0  0  0  0  0  0  0  0  0  0
        ///    2.4621   -0.8000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0
        ///    0.9405   -1.2944    0.0000 C   0  0  0  0  0  0  0  0  0  0  0
        ///    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0
        ///    0.9405    1.2944    0.0000 C   0  0  0  0  0  0  0  0  0  0  0
        ///    0.4460   -2.8161    0.0000 O   0  0  0  0  0  0  0  0  0  0  0
        ///   -1.1890   -1.0706    0.0000 O   0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string unknownstereo2 {
            get {
                return ResourceManager.GetString("unknownstereo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  Ketcher 10031320522D 1   1.00000     0.00000     0
        ///
        /// 26 28  0     0  0            999 V2000
        ///   -4.1521   -2.4191    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -3.2387   -2.8259    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -3.1340   -3.8203    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -2.4296   -2.2381    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -2.5342   -1.2436    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -1.5161   -2.6448    0.0000 C   0  0  0  0  0  0  0  0  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string v2000relativestereo {
            get {
                return ResourceManager.GetString("v2000relativestereo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  ChemDraw09261416452D
        ///
        ///  0  0  0     0  0              0 V3000
        ///M  V30 BEGIN CTAB
        ///M  V30 COUNTS 33 36 0 0 0
        ///M  V30 BEGIN ATOM
        ///M  V30 1 C -3.578644 0.199956 0.000000 0
        ///M  V30 2 C -3.578644 -0.625044 0.000000 0
        ///M  V30 3 C -2.864172 -1.037544 0.000000 0
        ///M  V30 4 C -2.149702 -0.625044 0.000000 0
        ///M  V30 5 C -2.149702 0.199956 0.000000 0
        ///M  V30 6 C -2.864172 0.612456 0.000000 0
        ///M  V30 7 C -1.435230 -1.037544 0.000000 0
        ///M  V30 8 C -0.720760 -0.625044 0.000000 0
        ///M  V30 9 C -0.720760 0.199956 0.00000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string v3000example {
            get {
                return ResourceManager.GetString("v3000example", resourceCulture);
            }
        }
    }
}
