// <auto-generated />
namespace RSC.Compounds.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddindextoExternalIdentiferinSubstances : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddindextoExternalIdentiferinSubstances));
        
        string IMigrationMetadata.Id
        {
            get { return "201510152202466_Add index to ExternalIdentifer in Substances"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
