//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSC.Compounds.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RSC.Compounds.Tests.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfInChI xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.datacontract.org/2004/07/RSC.Compounds&quot;&gt;
        ///  &lt;InChI&gt;
        ///    &lt;InChIKey&gt;HNEGCRMUYSKRRR-DAUWQXBBSA-N&lt;/InChIKey&gt;
        ///    &lt;Inchi&gt;InChI=1S/C17H24O4/c1-10-5-6-15(3)12(7-10)21-14-8-13(20-11(2)18)16(15,4)17(14)9-19-17/h7,12-14H,5-6,8-9H2,1-4H3/t12-,13-,14-,15+,16-,17?/m1/s1&lt;/Inchi&gt;
        ///  &lt;/InChI&gt;
        ///  &lt;InChI&gt;
        ///    &lt;InChIKey&gt;RTKIYFITIVXBLE-QEQCGCAPSA-N&lt;/InChIKey&gt;
        ///    &lt;Inchi&gt;InChI=1S/C17H22N2O3/c1-12(5 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InChIs {
            get {
                return ResourceManager.GetString("InChIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ArrayOfRecordData xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.datacontract.org/2004/07/RSC.Compounds&quot;&gt;
        ///  &lt;RecordData&gt;
        ///    &lt;Compound&gt;
        ///      &lt;Guid&gt;00000000-0000-0000-0000-000000000000&lt;/Guid&gt;
        ///      &lt;Id&gt;0&lt;/Id&gt;
        ///      &lt;Mol&gt;
        ///  -INDIGO-08041519062D
        ///
        ///  5  5  0  0  0  0  0  0  0  0999 V2000
        ///    0.5008    1.5428    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
        ///   -0.3065    0.9519    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
        ///    0.00 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string upload2gcn {
            get {
                return ResourceManager.GetString("upload2gcn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;$type&quot;: &quot;System.Collections.Generic.List`1[[RSC.Compounds.RecordData, RSC.Compounds.Core]], mscorlib&quot;,
        ///  &quot;$values&quot;: [
        ///    {
        ///      &quot;$type&quot;: &quot;RSC.Compounds.RecordData, RSC.Compounds.Core&quot;,
        ///      &quot;ExternalId&quot;: &quot;0&quot;,
        ///      &quot;Revision&quot;: {
        ///        &quot;$type&quot;: &quot;RSC.Compounds.Revision, RSC.Compounds.Core&quot;,
        ///        &quot;Version&quot;: 0,
        ///        &quot;DateCreated&quot;: &quot;2015-09-09T17:41:53.098039-04:00&quot;,
        ///        &quot;EmbargoDate&quot;: null,
        ///        &quot;Revoked&quot;: false,
        ///        &quot;Sdf&quot;: &quot;0\r\nCBDIGESTER1216131122\r\n\r\n 12 12  0  0000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string upload2gcnJSON {
            get {
                return ResourceManager.GetString("upload2gcnJSON", resourceCulture);
            }
        }
    }
}
