using System;
using System.Collections.Generic;

namespace ChemSpider.Web
{
	public class PickingLists
	{
		public static Dictionary<string, string> CountriesList()
		{
			Dictionary<string, string> contries = new Dictionary<string, string>();

			contries.Add("AF", "Afghanistan");
			contries.Add("AL", "Albania");
			contries.Add("DZ", "Algeria");
			contries.Add("AS", "American Samoa");
			contries.Add("AD", "Andorra");
			contries.Add("AO", "Angola");
			contries.Add("AI", "Anguilla");
			contries.Add("AQ", "Antarctica");
			contries.Add("AG", "Antigua and Barbuda");
			contries.Add("AR", "Argentina");
			contries.Add("AM", "Armenia");
			contries.Add("AW", "Aruba");
			contries.Add("AU", "Australia");
			contries.Add("AT", "Austria");
			contries.Add("AZ", "Azerbaijan");
			contries.Add("BS", "Bahamas");
			contries.Add("BH", "Bahrain");
			contries.Add("BD", "Bangladesh");
			contries.Add("BB", "Barbados");
			contries.Add("BY", "Belarus");
			contries.Add("BE", "Belgium");
			contries.Add("BZ", "Belize");
			contries.Add("BJ", "Benin");
			contries.Add("BM", "Bermuda");
			contries.Add("BT", "Bhutan");
			contries.Add("BO", "Bolivia");
			contries.Add("BA", "Bosnia-Herzegovina");
			contries.Add("BW", "Botswana");
			contries.Add("BR", "Brazil");
			contries.Add("BN", "Brunei Darussalam");
			contries.Add("BG", "Bulgaria");
			contries.Add("BF", "Burkina Faso");
			contries.Add("BI", "Burundi");
			contries.Add("KH", "Cambodia");
			contries.Add("CM", "Cameroon");
			contries.Add("CA", "Canada");
			contries.Add("CV", "Cape Verde");
			contries.Add("KY", "Cayman Islands");
			contries.Add("CF", "Central African Republic");
			contries.Add("TD", "Chad");
			contries.Add("CL", "Chile");
			contries.Add("CN", "China");
			contries.Add("CX", "Christmas Island");
			contries.Add("CC", "Cocos (Keeling) Islands");
			contries.Add("CO", "Colombia");
			contries.Add("KM", "Comoros");
            contries.Add("CD", "Democratic Republic of the Congo"); 
			contries.Add("CG", "Republic of the Congo");
			contries.Add("CK", "Cook Islands");
			contries.Add("CR", "Costa Rica");
			contries.Add("CI", "Cote D'Ivoire");
			contries.Add("HR", "Croatia");
			contries.Add("CU", "Cuba");
			contries.Add("CY", "Cyprus");
			contries.Add("CZ", "Czech Republic");
			contries.Add("DK", "Denmark");
			contries.Add("DJ", "Djibouti");
			contries.Add("DM", "Dominica");
			contries.Add("DO", "Dominican Republic");
			contries.Add("TP", "East Timor");
			contries.Add("EC", "Ecuador");
			contries.Add("EG", "Egypt");
			contries.Add("SV", "El Salvador");
			contries.Add("GQ", "Equatorial Guinea");
			contries.Add("ER", "Eritrea");
			contries.Add("EE", "Estonia");
			contries.Add("ET", "Ethiopia");
			contries.Add("FK", "Falkland Islands (Malvinas)");
			contries.Add("FO", "Faroe Islands");
			contries.Add("FJ", "Fiji");
			contries.Add("FI", "Finland");
			contries.Add("FR", "France");
			contries.Add("GF", "French Guiana");
			contries.Add("PF", "French Polynesia");
			contries.Add("TF", "French Southern Territories");
			contries.Add("GA", "Gabon");
			contries.Add("GM", "Gambia");
			contries.Add("GE", "Georgia");
			contries.Add("DE", "Germany");
			contries.Add("GH", "Ghana");
			contries.Add("GI", "Gibraltar");
			contries.Add("GR", "Greece");
			contries.Add("GL", "Greenland");
			contries.Add("GD", "Grenada");
			contries.Add("GP", "Guadeloupe");
			contries.Add("GU", "Guam");
			contries.Add("GT", "Guatemala");
			contries.Add("GN", "Guinea");
			contries.Add("GW", "Guinea-Bissau");
			contries.Add("GY", "Guyana");
			contries.Add("HT", "Haiti");
			contries.Add("HM", "Heard And Mc Donald Islands");
			contries.Add("VA", "Holy See (Vatican City State)");
			contries.Add("HN", "Honduras");
			contries.Add("HK", "Hong Kong");
			contries.Add("HU", "Hungary");
			contries.Add("IS", "Iceland");
			contries.Add("IN", "India");
			contries.Add("ID", "Indonesia");
			contries.Add("IR", "Iran (Islamic Republic Of)");
			contries.Add("IQ", "Iraq");
			contries.Add("IE", "Ireland");
			contries.Add("IL", "Israel");
			contries.Add("IT", "Italy");
			contries.Add("JM", "Jamaica");
			contries.Add("JP", "Japan");
			contries.Add("JO", "Jordan");
			contries.Add("KZ", "Kazakhstan");
			contries.Add("KE", "Kenya");
			contries.Add("KI", "Kiribati");
			contries.Add("KP", "Korea, Dem People's Republic");
			contries.Add("KR", "Korea, Republic Of");
			contries.Add("KW", "Kuwait");
			contries.Add("KG", "Kyrgyzstan");
			contries.Add("LA", "Lao People's Dem Republic");
			contries.Add("LV", "Latvia");
			contries.Add("LB", "Lebanon");
			contries.Add("LS", "Lesotho");
			contries.Add("LR", "Liberia");
			contries.Add("LY", "Libyan Arab Jamahiriya");
			contries.Add("LI", "Liechtenstein");
			contries.Add("LT", "Lithuania");
			contries.Add("LU", "Luxembourg");
			contries.Add("MO", "Macau");
			contries.Add("MK", "Macedonia");
			contries.Add("MG", "Madagascar");
			contries.Add("MW", "Malawi");
			contries.Add("MY", "Malaysia");
			contries.Add("MV", "Maldives");
			contries.Add("ML", "Mali");
			contries.Add("MT", "Malta");
			contries.Add("MH", "Marshall Islands");
			contries.Add("MQ", "Martinique");
			contries.Add("MR", "Mauritania");
			contries.Add("MU", "Mauritius");
			contries.Add("YT", "Mayotte");
			contries.Add("MX", "Mexico");
			contries.Add("FM", "Micronesia, Federated States");
			contries.Add("MD", "Moldova");
			contries.Add("MC", "Monaco");
			contries.Add("MN", "Mongolia");
			contries.Add("MS", "Montserrat");
			contries.Add("MA", "Morocco");
			contries.Add("MZ", "Mozambique");
			contries.Add("MM", "Myanmar");
			contries.Add("NA", "Namibia");
			contries.Add("NR", "Nauru");
			contries.Add("NP", "Nepal");
			contries.Add("NL", "Netherlands");
			contries.Add("AN", "Netherlands Antilles");
			contries.Add("NC", "New Caledonia");
			contries.Add("NZ", "New Zealand");
			contries.Add("NI", "Nicaragua");
			contries.Add("NE", "Niger");
			contries.Add("NG", "Nigeria");
			contries.Add("NU", "Niue");
			contries.Add("NF", "Norfolk Island");
			contries.Add("MP", "Northern Mariana Islands");
			contries.Add("NO", "Norway");
			contries.Add("OM", "Oman");
			contries.Add("PK", "Pakistan");
			contries.Add("PW", "Palau");
			contries.Add("PA", "Panama");
			contries.Add("PG", "Papua New Guinea");
			contries.Add("PY", "Paraguay");
			contries.Add("PE", "Peru");
			contries.Add("PH", "Philippines");
			contries.Add("PN", "Pitcairn Island");
			contries.Add("PL", "Poland");
			contries.Add("PT", "Portugal");
			contries.Add("PR", "Puerto Rico");
			contries.Add("QA", "Qatar");
			contries.Add("RE", "Reunion");
			contries.Add("RO", "Romania");
			contries.Add("RU", "Russian Federation");
			contries.Add("RW", "Rwanda");
			contries.Add("KN", "Saint Kitts And Nevis");
			contries.Add("LC", "Saint Lucia");
			contries.Add("VC", "Saint Vincent and The Grenadines");
			contries.Add("WS", "Samoa");
			contries.Add("SM", "San Marino");
			contries.Add("ST", "Sao Tome and Principe");
			contries.Add("SA", "Saudi Arabia");
			contries.Add("SN", "Senegal");
			contries.Add("SC", "Seychelles");
			contries.Add("SL", "Sierra Leone");
			contries.Add("SG", "Singapore");
			contries.Add("SK", "Slovakia");
			contries.Add("SI", "Slovenia");
			contries.Add("SB", "Solomon Islands");
			contries.Add("SO", "Somalia");
			contries.Add("ZA", "South Africa");
			contries.Add("GS", "South Georgia , S Sandwich Is.");
			contries.Add("ES", "Spain");
			contries.Add("LK", "Sri Lanka");
			contries.Add("SH", "St. Helena");
			contries.Add("PM", "St. Pierre And Miquelon");
			contries.Add("SD", "Sudan");
			contries.Add("SR", "Suriname");
			contries.Add("SJ", "Svalbard, Jan Mayen Islands");
			contries.Add("SZ", "Swaziland");
			contries.Add("SE", "Sweden");
			contries.Add("CH", "Switzerland");
			contries.Add("SY", "Syrian Arab Republic");
			contries.Add("TW", "Taiwan");
			contries.Add("TJ", "Tajikistan");
			contries.Add("TZ", "Tanzania, United Republic Of");
			contries.Add("TH", "Thailand");
			contries.Add("TG", "Togo");
			contries.Add("TK", "Tokelau");
			contries.Add("TO", "Tonga");
			contries.Add("TT", "Trinidad And Tobago");
			contries.Add("TN", "Tunisia");
			contries.Add("TR", "Turkey");
			contries.Add("TM", "Turkmenistan");
			contries.Add("TC", "Turks And Caicos Islands");
			contries.Add("TV", "Tuvalu");
			contries.Add("UG", "Uganda");
			contries.Add("UA", "Ukraine");
			contries.Add("AE", "United Arab Emirates");
			contries.Add("GB", "United Kingdom");
			contries.Add("US", "United States");
			contries.Add("UM", "United States Minor Is.");
			contries.Add("UY", "Uruguay");
			contries.Add("UZ", "Uzbekistan");
			contries.Add("VU", "Vanuatu");
			contries.Add("VE", "Venezuela");
			contries.Add("VN", "Viet Nam");
			contries.Add("VG", "Virgin Islands (British)");
			contries.Add("VI", "Virgin Islands (U.S.)");
			contries.Add("WF", "Wallis And Futuna Islands");
			contries.Add("EH", "Western Sahara");
			contries.Add("YE", "Yemen");
			contries.Add("YU", "Yugoslavia");
			contries.Add("ZM", "Zambia");
			contries.Add("ZW", "Zimbabwe");

			return contries;
		}
	}
}
