//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVSPTests.CVSPWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CVSP_Processing_Type", Namespace="http://tempuri.org/")]
    public enum CVSP_Processing_Type : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RulesOnly = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InChIOnly = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RulesAndInChI = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LayoutOnly = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CVSPWebService.ChemicalValidationSoap")]
    public interface ChemicalValidationSoap {
        
        // CODEGEN: Generating message contract since element name sdf_text from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/submitSDF4Processing", ReplyAction="*")]
        CVSPTests.CVSPWebService.submitSDF4ProcessingResponse submitSDF4Processing(CVSPTests.CVSPWebService.submitSDF4ProcessingRequest request);
        
        // CODEGEN: Generating message contract since element name dep_guid from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/isSubmissionProcessed_WS_CVSP", ReplyAction="*")]
        CVSPTests.CVSPWebService.isSubmissionProcessed_WS_CVSPResponse isSubmissionProcessed_WS_CVSP(CVSPTests.CVSPWebService.isSubmissionProcessed_WS_CVSPRequest request);
        
        // CODEGEN: Generating message contract since element name dep_guid from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getValidationLogs_WS_CVSP", ReplyAction="*")]
        CVSPTests.CVSPWebService.getValidationLogs_WS_CVSPResponse getValidationLogs_WS_CVSP(CVSPTests.CVSPWebService.getValidationLogs_WS_CVSPRequest request);
        
        // CODEGEN: Generating message contract since element name dep_guid from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getStandardizedStructure_WS_CVSP", ReplyAction="*")]
        CVSPTests.CVSPWebService.getStandardizedStructure_WS_CVSPResponse getStandardizedStructure_WS_CVSP(CVSPTests.CVSPWebService.getStandardizedStructure_WS_CVSPRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class submitSDF4ProcessingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="submitSDF4Processing", Namespace="http://tempuri.org/", Order=0)]
        public CVSPTests.CVSPWebService.submitSDF4ProcessingRequestBody Body;
        
        public submitSDF4ProcessingRequest() {
        }
        
        public submitSDF4ProcessingRequest(CVSPTests.CVSPWebService.submitSDF4ProcessingRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class submitSDF4ProcessingRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sdf_text;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public CVSPTests.CVSPWebService.CVSP_Processing_Type std_type;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string token;
        
        public submitSDF4ProcessingRequestBody() {
        }
        
        public submitSDF4ProcessingRequestBody(string sdf_text, CVSPTests.CVSPWebService.CVSP_Processing_Type std_type, string token) {
            this.sdf_text = sdf_text;
            this.std_type = std_type;
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class submitSDF4ProcessingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="submitSDF4ProcessingResponse", Namespace="http://tempuri.org/", Order=0)]
        public CVSPTests.CVSPWebService.submitSDF4ProcessingResponseBody Body;
        
        public submitSDF4ProcessingResponse() {
        }
        
        public submitSDF4ProcessingResponse(CVSPTests.CVSPWebService.submitSDF4ProcessingResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class submitSDF4ProcessingResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string submitSDF4ProcessingResult;
        
        public submitSDF4ProcessingResponseBody() {
        }
        
        public submitSDF4ProcessingResponseBody(string submitSDF4ProcessingResult) {
            this.submitSDF4ProcessingResult = submitSDF4ProcessingResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isSubmissionProcessed_WS_CVSPRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isSubmissionProcessed_WS_CVSP", Namespace="http://tempuri.org/", Order=0)]
        public CVSPTests.CVSPWebService.isSubmissionProcessed_WS_CVSPRequestBody Body;
        
        public isSubmissionProcessed_WS_CVSPRequest() {
        }
        
        public isSubmissionProcessed_WS_CVSPRequest(CVSPTests.CVSPWebService.isSubmissionProcessed_WS_CVSPRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class isSubmissionProcessed_WS_CVSPRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string dep_guid;
        
        public isSubmissionProcessed_WS_CVSPRequestBody() {
        }
        
        public isSubmissionProcessed_WS_CVSPRequestBody(string dep_guid) {
            this.dep_guid = dep_guid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isSubmissionProcessed_WS_CVSPResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isSubmissionProcessed_WS_CVSPResponse", Namespace="http://tempuri.org/", Order=0)]
        public CVSPTests.CVSPWebService.isSubmissionProcessed_WS_CVSPResponseBody Body;
        
        public isSubmissionProcessed_WS_CVSPResponse() {
        }
        
        public isSubmissionProcessed_WS_CVSPResponse(CVSPTests.CVSPWebService.isSubmissionProcessed_WS_CVSPResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class isSubmissionProcessed_WS_CVSPResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool isSubmissionProcessed_WS_CVSPResult;
        
        public isSubmissionProcessed_WS_CVSPResponseBody() {
        }
        
        public isSubmissionProcessed_WS_CVSPResponseBody(bool isSubmissionProcessed_WS_CVSPResult) {
            this.isSubmissionProcessed_WS_CVSPResult = isSubmissionProcessed_WS_CVSPResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getValidationLogs_WS_CVSPRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getValidationLogs_WS_CVSP", Namespace="http://tempuri.org/", Order=0)]
        public CVSPTests.CVSPWebService.getValidationLogs_WS_CVSPRequestBody Body;
        
        public getValidationLogs_WS_CVSPRequest() {
        }
        
        public getValidationLogs_WS_CVSPRequest(CVSPTests.CVSPWebService.getValidationLogs_WS_CVSPRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getValidationLogs_WS_CVSPRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string dep_guid;
        
        public getValidationLogs_WS_CVSPRequestBody() {
        }
        
        public getValidationLogs_WS_CVSPRequestBody(string dep_guid) {
            this.dep_guid = dep_guid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getValidationLogs_WS_CVSPResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getValidationLogs_WS_CVSPResponse", Namespace="http://tempuri.org/", Order=0)]
        public CVSPTests.CVSPWebService.getValidationLogs_WS_CVSPResponseBody Body;
        
        public getValidationLogs_WS_CVSPResponse() {
        }
        
        public getValidationLogs_WS_CVSPResponse(CVSPTests.CVSPWebService.getValidationLogs_WS_CVSPResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getValidationLogs_WS_CVSPResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CVSPTests.CVSPWebService.ArrayOfString getValidationLogs_WS_CVSPResult;
        
        public getValidationLogs_WS_CVSPResponseBody() {
        }
        
        public getValidationLogs_WS_CVSPResponseBody(CVSPTests.CVSPWebService.ArrayOfString getValidationLogs_WS_CVSPResult) {
            this.getValidationLogs_WS_CVSPResult = getValidationLogs_WS_CVSPResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getStandardizedStructure_WS_CVSPRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getStandardizedStructure_WS_CVSP", Namespace="http://tempuri.org/", Order=0)]
        public CVSPTests.CVSPWebService.getStandardizedStructure_WS_CVSPRequestBody Body;
        
        public getStandardizedStructure_WS_CVSPRequest() {
        }
        
        public getStandardizedStructure_WS_CVSPRequest(CVSPTests.CVSPWebService.getStandardizedStructure_WS_CVSPRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getStandardizedStructure_WS_CVSPRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string dep_guid;
        
        public getStandardizedStructure_WS_CVSPRequestBody() {
        }
        
        public getStandardizedStructure_WS_CVSPRequestBody(string dep_guid) {
            this.dep_guid = dep_guid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getStandardizedStructure_WS_CVSPResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getStandardizedStructure_WS_CVSPResponse", Namespace="http://tempuri.org/", Order=0)]
        public CVSPTests.CVSPWebService.getStandardizedStructure_WS_CVSPResponseBody Body;
        
        public getStandardizedStructure_WS_CVSPResponse() {
        }
        
        public getStandardizedStructure_WS_CVSPResponse(CVSPTests.CVSPWebService.getStandardizedStructure_WS_CVSPResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getStandardizedStructure_WS_CVSPResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getStandardizedStructure_WS_CVSPResult;
        
        public getStandardizedStructure_WS_CVSPResponseBody() {
        }
        
        public getStandardizedStructure_WS_CVSPResponseBody(string getStandardizedStructure_WS_CVSPResult) {
            this.getStandardizedStructure_WS_CVSPResult = getStandardizedStructure_WS_CVSPResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ChemicalValidationSoapChannel : CVSPTests.CVSPWebService.ChemicalValidationSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChemicalValidationSoapClient : System.ServiceModel.ClientBase<CVSPTests.CVSPWebService.ChemicalValidationSoap>, CVSPTests.CVSPWebService.ChemicalValidationSoap {
        
        public ChemicalValidationSoapClient() {
        }
        
        public ChemicalValidationSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ChemicalValidationSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChemicalValidationSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChemicalValidationSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CVSPTests.CVSPWebService.submitSDF4ProcessingResponse CVSPTests.CVSPWebService.ChemicalValidationSoap.submitSDF4Processing(CVSPTests.CVSPWebService.submitSDF4ProcessingRequest request) {
            return base.Channel.submitSDF4Processing(request);
        }
        
        public string submitSDF4Processing(string sdf_text, CVSPTests.CVSPWebService.CVSP_Processing_Type std_type, string token) {
            CVSPTests.CVSPWebService.submitSDF4ProcessingRequest inValue = new CVSPTests.CVSPWebService.submitSDF4ProcessingRequest();
            inValue.Body = new CVSPTests.CVSPWebService.submitSDF4ProcessingRequestBody();
            inValue.Body.sdf_text = sdf_text;
            inValue.Body.std_type = std_type;
            inValue.Body.token = token;
            CVSPTests.CVSPWebService.submitSDF4ProcessingResponse retVal = ((CVSPTests.CVSPWebService.ChemicalValidationSoap)(this)).submitSDF4Processing(inValue);
            return retVal.Body.submitSDF4ProcessingResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CVSPTests.CVSPWebService.isSubmissionProcessed_WS_CVSPResponse CVSPTests.CVSPWebService.ChemicalValidationSoap.isSubmissionProcessed_WS_CVSP(CVSPTests.CVSPWebService.isSubmissionProcessed_WS_CVSPRequest request) {
            return base.Channel.isSubmissionProcessed_WS_CVSP(request);
        }
        
        public bool isSubmissionProcessed_WS_CVSP(string dep_guid) {
            CVSPTests.CVSPWebService.isSubmissionProcessed_WS_CVSPRequest inValue = new CVSPTests.CVSPWebService.isSubmissionProcessed_WS_CVSPRequest();
            inValue.Body = new CVSPTests.CVSPWebService.isSubmissionProcessed_WS_CVSPRequestBody();
            inValue.Body.dep_guid = dep_guid;
            CVSPTests.CVSPWebService.isSubmissionProcessed_WS_CVSPResponse retVal = ((CVSPTests.CVSPWebService.ChemicalValidationSoap)(this)).isSubmissionProcessed_WS_CVSP(inValue);
            return retVal.Body.isSubmissionProcessed_WS_CVSPResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CVSPTests.CVSPWebService.getValidationLogs_WS_CVSPResponse CVSPTests.CVSPWebService.ChemicalValidationSoap.getValidationLogs_WS_CVSP(CVSPTests.CVSPWebService.getValidationLogs_WS_CVSPRequest request) {
            return base.Channel.getValidationLogs_WS_CVSP(request);
        }
        
        public CVSPTests.CVSPWebService.ArrayOfString getValidationLogs_WS_CVSP(string dep_guid) {
            CVSPTests.CVSPWebService.getValidationLogs_WS_CVSPRequest inValue = new CVSPTests.CVSPWebService.getValidationLogs_WS_CVSPRequest();
            inValue.Body = new CVSPTests.CVSPWebService.getValidationLogs_WS_CVSPRequestBody();
            inValue.Body.dep_guid = dep_guid;
            CVSPTests.CVSPWebService.getValidationLogs_WS_CVSPResponse retVal = ((CVSPTests.CVSPWebService.ChemicalValidationSoap)(this)).getValidationLogs_WS_CVSP(inValue);
            return retVal.Body.getValidationLogs_WS_CVSPResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CVSPTests.CVSPWebService.getStandardizedStructure_WS_CVSPResponse CVSPTests.CVSPWebService.ChemicalValidationSoap.getStandardizedStructure_WS_CVSP(CVSPTests.CVSPWebService.getStandardizedStructure_WS_CVSPRequest request) {
            return base.Channel.getStandardizedStructure_WS_CVSP(request);
        }
        
        public string getStandardizedStructure_WS_CVSP(string dep_guid) {
            CVSPTests.CVSPWebService.getStandardizedStructure_WS_CVSPRequest inValue = new CVSPTests.CVSPWebService.getStandardizedStructure_WS_CVSPRequest();
            inValue.Body = new CVSPTests.CVSPWebService.getStandardizedStructure_WS_CVSPRequestBody();
            inValue.Body.dep_guid = dep_guid;
            CVSPTests.CVSPWebService.getStandardizedStructure_WS_CVSPResponse retVal = ((CVSPTests.CVSPWebService.ChemicalValidationSoap)(this)).getStandardizedStructure_WS_CVSP(inValue);
            return retVal.Body.getStandardizedStructure_WS_CVSPResult;
        }
    }
}
